### ISSUE TITLE
VRLayer.type, VRLayer.srcBlend / dstBlend, VRLayer.flags in 2.0?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#1]
As far as I can tell, currently there is no way to distinguish one layer from another in terms of their types, all of them seem to be equal. This doesn't make much sense for Oculus, because we have several layer types (such as eye buffer, cylinder layer, loading icon layer, etc).  Moreover, each layer may have its own srcBlend / dstBlend settings, it could have flags (head-locked, Chromatic Aberration correction on/off, spinning on/off, etc). How this supposed to be handled in 2.0?

**Comment by cabanier** [comment]
Closing since the new API implements this in a more WebXR way
