### ISSUE TITLE
Define XRProjectionLayer as a replacement for XRWebGLLayer

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#11]
The new XRProjectionLayer should be using XRImageSource (issue #10 ) and must be constructed by the XRLayerFactory (issue #5 ). The main benefit will be higher flexibility in terms of how rendering is done (i.e. into a framebuffer, texture or texture array). Theoretically, even WebGPU image sources could be made available.

**Comment by cabanier** [comment]
This is covered by the initial proposal
