### ISSUE TITLE
Add fixed foveation optional attribute to ProjectionLayer

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#112]
Some HW allows to use so called 'fixed foveation rendering' (FFR) techniques, applicable only to projection layer. Basically, the idea behind it is to render less on borders (vision periphery) than in the center. It is handled by the GL driver, it is pretty much free and requires no modifications to shaders (unlike multiview) and it saves GPU perf (while multiview saves CPU). GL driver just rasterizes with less resolution at periphery (on tile basis for mobile). 

There could be different levels of FFR applied, the higher level is the more visible artifacts are but the more perf is gained. Depending on content's complexity the win could be up to 25% of GPU time.

We can specify it by float 0.0 ... 1.0f, where 0.0 indicates no foveation and 1.0 - max possible level. For example in Oculus we currently have 4 levels: no foveation, low, mid, high, which will translate to 0.0, 0.3, 0.6, 1.0. If something like 0.5 specified then UA can decide which actual level to select (but this will be vendor and HW-specific, I assume).

As I said, it makes sense only for ProjectionLayers.

**Comment by cabanier** [comment]
Is this something specific to Oculus or is it generally available?
Also, do you have a link to a description of this property?

**Comment by Artyom17** [comment]
It is not Oculus-specific, but it is not very widely available either. Basically, this feature is based on QCOM GL extension (and Vulkan version is available too) - https://www.khronos.org/registry/OpenGL/extensions/QCOM/QCOM_texture_foveated.txt

**Comment by Artyom17** [comment]
Here is the link to description of this extension for WebVR: https://developer.oculus.com/documentation/oculus-browser/browser-optimize-rendering/

**Comment by cabanier** [comment]
> It is not Oculus-specific, but it is not very widely available either. Basically, this feature is based on QCOM GL extension (and Vulkan version is available too) - https://www.khronos.org/registry/OpenGL/extensions/QCOM/QCOM_texture_foveated.txt

It seems there are a lot of potential flags that are not always applicable to all devices (ie does a phone need `chromaticAberrationCorrection`?)
Instead of adding various attributes, maybe we can provide some sort of mechanism to let the author know what features are available and then let them control them.

It could look like this:
```webidl
partial interface XRCompositionLayer {
  readonly attribute FrozenArray<DOMString> extensions;
  any getExtension(DOMString);
  void setExtension(DOMString, any);
};
```

**Comment by cabanier** [comment]
/agenda should we have an extension mechanism for layers to deal with device specific settings?

**Comment by Artyom17** [comment]
I like this idea. I wouldn't probably call it 'extensions'. Maybe, call it 'features'?

**Comment by cabanier** [comment]
People didn't seem overly excited about adding extensions/features to the spec.
Instead, the consensus was to created some sort of initial parameters that are set if the implementation supports them.
More discussion is needed but I will put up a strawman proposal after #83
