### ISSUE TITLE
Decide if media streams are better than video elements

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#117]
@Manishearth proposed in PR #115 that media streams might be better suited than regular <video> elements.
We need to investigate the cost/benefit of that approach.

**Comment by cabanier** [comment]
We've gotten feedback from our customers stating that switching to media stream would be a lot more work with no discernible benefit.
Let's close this for now and we can revisit it in the future when there's a stronger use case. @Manishearth , does that sound reasonable?

**Comment by Manishearth** [comment]
Sounds good.

**Comment by AdaRoseCannon** [comment]
Video elements can have a Media stream given to them via `URL.createObjectURL()` so this probabvly would not preclude media streams I presume?

**Comment by cabanier** [comment]
> Video elements can have a Media stream given to them via `URL.createObjectURL()` so this probabvly would not preclude media streams I presume?

Correct, you can still use them if you want.
