### ISSUE TITLE
Move ignoreDepthValues to CompositionLayer

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#119]
Since depth buffer can be requested for virtually any type of layer, we need to move the 'ignoreDepthValues' hint to the CompositionLayer. This flag will indicate that the depth buffer can be safely discarded at the end of rAF OR when another fbo is being bound to the WebGL context. This may save a lot of GPU perf.

**Comment by cabanier** [comment]
The spec defines that only depth buffers for projection layers can be used by the compositor.
This means that `ignoreDepthValues` is always true for all other layer types.

**Comment by Artyom17** [comment]
oh... ok, that makes sense, I think
