### ISSUE TITLE
Is there some overlap with DOM Overlays here ?

### ISSUE THREAD

**Issue by raviramachandra** [immersive-web/layers#12]
Wanted to know if we have some overlap with Layers and DOM Overlay. Could we make a 'Overlay Layer' render a DOM ? Any thoughts ?

**Comment by avaer** [comment]
That's how we always did it on Magic Leap. But I remember the standards pushback from that was that drawing DOM in XR is an insurmountable security challenge.

**Comment by cabanier** [comment]
yes, as we discussed during the F2F, we can borrow the mitigations that @klausw introduced for DOM Overlays.
However, it will not be enough because we need to think about how controller input will work with layers.

**Comment by cabanier** [comment]
@raviramachandra we will address DOM layers in a future revision of the spec.
At that time, we'll revisit if there's overlap with DOM overlay.

I will close this issue for now. I wish there was a way to give it another status so we wouldn't lose track.
Let me know if you disagree.
