### ISSUE TITLE
viewPixelWidth and viewPixelHeight semantics?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#123]
https://immersive-web.github.io/layers/#dom-xrcompositionlayer-viewpixelwidth says that "The viewPixelWidth and viewPixelHeight attributes return the width and height of the GL attachments, respectively. If there are no attachments, they will return 0."

What should these return if called outside an rAF? (There may or may not be GL attachments outside of an rAF, depending on the implementation).

For `stereo-left-right` and `stereo-top-bottom` are these the dimensions of one eye, or the dimensions of the whole texture?

**Comment by asajeffrey** [comment]
It's not obvious to me why these are part of a layer, rather than part of a subimage..

**Comment by cabanier** [comment]
> For `stereo-left-right` and `stereo-top-bottom` are these the dimensions of one eye, or the dimensions of the whole texture?

That was discussed in #85 and we concluded that it should be the value per eye which is why we renamed it to **view**PixelWidth

**Comment by cabanier** [comment]
> It's not obvious to me why these are part of a layer, rather than part of a subimage.

You are correct. These should be on XRSubImage or XRWebGLSubImage.
Pixel width and height are supplied by XRWebGLBinding so I think it should be the latter. What do you think?

**Comment by asajeffrey** [comment]
I can imagine other back ends wanting to use non-pixel units, so it probably makes sense for it to be `XRWebGLBinding`.
