### ISSUE TITLE
XRQuadLayer and XRCylinderLayer initialize position.x to 1.0

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/layers#126]
The algorithm for initializing each new `XRQuadLayer` and `XRCylinderLayer` sets its `transform`'s `position` to `{ x: 1.0, y: 0.0, z: 0.0, w: 1.0 }`.

Should this be `{ x: 0.0, y: 0.0, z: 0.0, w: 1.0 }`?

**Comment by cabanier** [comment]
The initial offset of `XRCylinderLayer` should indeed be `{ x: 0.0, y: 0.0, z: 0.0, w: 1.0 }` but the quadlayer should be `{ x: 1.0, y: 0.0, z: 0.0, w: 1.0 }`.
Otherwise the default quad would likely be where the viewer is.

**Comment by thetuvix** [comment]
I expect many WebXR quads to be placed directly in anchor spaces, especially now that the API has apps explicitly specify each layer's `XRSpace`. (thanks!)

It will be surprising to developers to have the user place an anchor on a wall, set that anchor space on their quad to place it exactly there, and then have it appear 1 meter to the right unless they explicitly set the transform to identity.

**Comment by cabanier** [comment]
> It will be surprising to developers to have the user place an anchor on a wall, set that anchor space on their quad to place it exactly there, and then have it appear 1 meter to the right unless they explicitly set the transform to identity.

If an author gets the anchor from a wall and places a cylinder or quad layer, they will always have to change the transform to get reasonable behavior.
Thinking about it some more though, I agree that we shouldn't have this extra offset for quads as that might be confusing. I will make the change.
