### ISSUE TITLE
Define a maximum number of concurrent layers

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#129]
As mentioned by @thetuvix in #127 , [OpenXR](https://github.com/KhronosGroup/OpenXR-SDK/blob/master/include/openxr/openxr.h#L135) states that an implementation must support a minimum of 16 layers but some implementations only support a single projection layer.

Should the spec define a minimum number of layers? Should it have a maximum?

**Comment by cabanier** [comment]
After discussing this with @Artyom17, we'd like to propose that UA should support a minimum of 10 layers. Any layers created after that, might get an error upon creation.

The reason is that the OS might be using some layers for its own purposes and there's a system wide limit of 16.
@toji , @Manishearth , what do you think?

**Comment by toji** [comment]
I'm a little worried for what this might mean for UAs that aren't OpenXR-backed. Forcing the UA to handle the compositing for 10+ layers at all times seems light a high bar for implementers, especially when we've got feedback from Mozilla already saying they're concerned about the complexity of implementing this module.

Also, I'm a little concerned that a single "layer count" limit might be a bit too simplistic? As you said, there may be systems where only a single projection layer is supported, so we'd have to think about how to communicate that as part of the overall limits, and it seems like there's very likely some scenarios where N layers works fine but N+1, even though technically supported, may fall into a slow path or a low quality path. (Such as the native compositor no longer supporting that many layers, so you fall back to the UA doing the compositing.)

**Comment by cabanier** [comment]
Should we stay silent then for now? We can always revisit it later.

**Comment by cabanier** [comment]
It's too early to make a good call on what a reasonable number is. I will close the issue and we can re-open once we have implementor feedback
