### ISSUE TITLE
Are different layers allowed to come from different WebGL contexts?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#130]
In https://immersive-web.github.io/layers/#updaterenderstatechanges there's no check that all of the layers came from the same WebGL context. Is it intended that this should be allowed?

**Comment by asajeffrey** [comment]
I can imagine some back ends being unhappy about having to perform composition on textures coming from different contexts, for example it may require all XR compatible WebGL contexts to support texture sharing.

**Comment by cabanier** [comment]
> In https://immersive-web.github.io/layers/#updaterenderstatechanges there's no check that all of the layers came from the same WebGL context. Is it intended that this should be allowed?

Yes. We discussed this at some point and concluded that this should be allowed since you can already have more than one context on a page.

**Comment by asajeffrey** [comment]
@cabanier er, so how am I meant to implement compositing on platforms that don't support texture sharing?

The canvas API is set up so you can never combine textures from different contexts, which is why it's fine to have more than one canvas on the page, but for layers we need to composite them which is going to be hard if they're from different contexts.

**Comment by cabanier** [comment]
I think some context is missing.
Layers are typically backed by swapchains which means that the xr compositor doesn't even know what context originally drew into the texture.

Moreover, the backing surfaces of different canvases with different context can be composited together on a regular HTML page. Maybe you have a different workflow for WebXR that bypasses this?

**Comment by asajeffrey** [comment]
@cabanier I'm thinking about the case where the browser is doing the compositing, because the back end doesn't support layers.

The workflow I'd envisioned was that each layer would be backed by a texture (or a texture array, as appropriate) and at the end of the frame we'd composite the layers together to the render target. This is fine, except that if the API allows different textures to come from different contexts then layers have to be backed by something that can be composited.

We could use swap chains for all layers, which would address the sharing, but will require allocating potentially twice as much texture memory.

**Comment by asajeffrey** [comment]
Hmm, perhaps we could have each layer backed by a surface rather than a texture, which would allow them to be composited without using texture sharing? I'll try it and see if I can get it to fly.

**Comment by cabanier** [comment]
@asajeffrey Can I close this issue for now? We can revisit later if you run into roadblocks.

**Comment by asajeffrey** [comment]
OK, I did some preliminary work, the good news is I think we can share surfaces, yay. The bad news is that the implementation has to jump through hoops. For example, the obvious way to implement the function which begins a frame is to make the GL context for the layers current, then do stuff in that context. Unfortunately, we can't do that because the layers might come from different contexts.

So while yes, I think we could get it to work, it's adding quite a bit of complexity. Do we have any use-cases where content creators want different layers to come from different WebGL contexts?

**Comment by cabanier** [comment]
> So while yes, I think we could get it to work, it's adding quite a bit of complexity. Do we have any use-cases where content creators want different layers to come from different WebGL contexts?

I do not. However, because we also have media layers with protected content, you will have to deal with mixed contexts and secure surfaces in your implementation.

**Comment by asajeffrey** [comment]
> I do not. However, because we also have media layers with protected content, you will have to deal with mixed contexts and secure surfaces in your implementation.

True, but I think we're going to need a completely separate code path for those anyway, since they don't have a GL context associated with them.

**Comment by avaer** [comment]
> Do we have any use-cases where content creators want different layers to come from different WebGL contexts?

Yes, we have a runtime that uses isolated WebGL contexts between different user applications that control the context. This is an important feature to get right at the spec level.

At Exokit our customers have been using emulated WebXR layers for a couple of years to do multi-app compositing. For this we've implemented various userland techniques including WebGL context switch emulation as mentioned. But these are all inferior solutions to getting this important use case handled in the spec.

**Comment by cabanier** [comment]
It sounds like there are use cases to have support for more than one context and it is implementable.
@asajeffrey I will close this issue. If this turns out to become an issue, feel free to reopen.
