### ISSUE TITLE
equirect parameterization

### ISSUE THREAD

**Issue by casseveritt** [immersive-web/layers#131]
The parameterization of equirect, in particular its scale and bias parameters, are a bit awkward.  The functionality they provide allows the layer to define a sub-region of the sphere that is visible. A more natural way to parameterize this would be to have a centralHorizontalAngle and an upperVerticalAngle and a lowerVerticalAngle.

**Comment by cabanier** [comment]
I agree that these parameters are awkward.
Would this IDL be more in line with your thoughts:

```webidl
interface XREquirectLayer : XRCompositionLayer {
  attribute XRSpace space;
  attribute XRRigidTransform transform;

  attribute float radius;
  attribute float centralHorizontalAngle;
  attribute float upperVerticalAngle;
  attribute float lowerVerticalAngle ;

  // Events
  attribute EventHandler onredraw;
};
```

**Comment by casseveritt** [comment]
Yes, I think that parameterization is clearer.

**Comment by Artyom17** [comment]
@casseveritt How do these params recalculated to the bias / scale (or texture matrix)? What if I just need to shift the texture (i.e. apply bias), how would this translate to these new params? I need to understand math behind these. Do you have an example of implementation of these for mobile SDK?

**Comment by casseveritt** [comment]
I don't have an implementation of these yet, however, a unity scale and bias would transform (x,y,z) from the unit sphere to a (u,v) of [0,1] in each direction.  If you scale by 2 in v, that would mean that only one hemisphere in longitude would be visible.  That would be what was the u = [0,0.5] range before.  To make the other hemisphere visible, you'd still use a scale of 2, but you'd use a bias of -1.

With v, it's the same idea. You scale by the reciprocal of the fraction of latitude you want visible. So, if you only wanted 60 degrees of latitude (out of 180), you'd scale by 3.  If you wanted visible range to be +/- 30 degrees, the bias would be -1.  If you wanted the visible range to be between 0 and 60, the bias would be -1.5.

Does that make sense?

Hopefully you can see why the horizontal and vertical angle parameterization is more intuitive. :-)

**Comment by Artyom17** [comment]
@casseveritt No doubts the angles parameterization is more intuitive, I am just trying to understand the math. It mostly makes sense to me at the moment (considering that it is Friday evening!). I still don't get how to use those two vertical angles and why there are two of them? Why vertical angle is not symmetrical like the horizontal one? 
It would be super helpful if you could provide the conversion math from the new params to the old bias/scale ones.

**Comment by Artyom17** [comment]
@casseveritt This is what I came up with for the math. I am pretty sure the math is correct for the central angle (I've tested it), but I am pretty confused about the vertical angles, because I don't quite understand what those angles mean, so that math could be completely wrong:

```javascript
      function eqr_angles_to_bias_scale(eqrlayer, central_angle, upper_vert_angle, lower_vert_angle) {
        const hemifrac = central_angle / (2.0 * Math.PI);
        upper_vert_angle = (upper_vert_angle + Math.PI / 2.0)
        lower_vert_angle = (lower_vert_angle + Math.PI / 2.0)
        const total_vert_angle = upper_vert_angle + lower_vert_angle;
        const upper_vertscale = upper_vert_angle / Math.PI;
        const lower_vertscale = lower_vert_angle / Math.PI;
        const vert_scale = total_vert_angle / (2.0 * Math.PI);
        const vert_offset = upper_vert_angle / total_vert_angle;
        let trans1 = mat4.create();
        let trans2 = mat4.create();
        let scale = mat4.create();
        mat4.fromTranslation(trans1, [ -0.5, -vert_offset, 0.0 ]);
        mat4.fromTranslation(trans2, [  0.5,  vert_offset, 0.0 ]);
        mat4.fromScaling(scale, [hemifrac, vert_scale, 1.0]);
        let inv_tex_mat = mat4.create();
        mat4.multiply(inv_tex_mat, scale, trans1);
        mat4.multiply(inv_tex_mat, trans2, inv_tex_mat);
        let tex_mat = mat4.create();
        mat4.invert(tex_mat, inv_tex_mat);

        let scaling = vec3.create();
        mat4.getScaling(scaling, tex_mat);

        let trans = vec3.create();
        mat4.getTranslation(trans, tex_mat);

        eqrlayer.scaleX = scaling[0];
        eqrlayer.scaleY = scaling[1];
        eqrlayer.biasX = trans[0];
        eqrlayer.biasY = trans[1];
      }
```

**Comment by casseveritt** [comment]
Without the benefit of being able to debug, this is what I'd say the math should be:
`
uscale = (2.0 * pi) / centralHorizontalAngle;
ubias = 0;
vscale = pi / (upperVerticalAngle - lowerVerticalAngle);
vbias = -(lowerVerticalAngle/pi + 0.5);
`
If the full mapping of 2pi horizontal and -pi/2 to pi/2 vertically maps to [0,1] in uv, then what we want is the scale and bias necessary to map a sub-window of that [0,1] range to [0,1].

**Comment by cabanier** [comment]
@Artyom17 are you ok with the new definition? Is it implementable on top of the older API?

**Comment by Artyom17** [comment]
@casseveritt I am not sure this is correct math, even for the central horizontal angle. ubias can't be just 0. For example, if the angle = PI, the result should be: uscale = 2, vscale = 1, ubias = -0.5, vbias = 0.

**Comment by casseveritt** [comment]
Yeah, given that you want the horizontal angle to be symmetric about the zero angle, you need a bias of (0.5 - uscale * 0.5).

**Comment by casseveritt** [comment]
I sketched this to illustrate the meaning of the angle parameters.  Does it make sense?

![Screenshot from 2020-05-12 16-34-54](https://user-images.githubusercontent.com/1714378/81748039-c45d8c80-946e-11ea-8a21-a615b69f19c1.png)

**Comment by Artyom17** [comment]
Ok, so the actual math is:
```
            eqrlayer.scaleX = (2.0 * Math.PI) / centralHorizontalAngle;
            eqrlayer.scaleY = Math.PI / (upperVerticalAngle - lowerVerticalAngle);
            eqrlayer.biasX = 0.5 - eqrlayer.scaleX * 0.5;
            // the image origin is in the upper left
            const upperFrac = 0.5 - (upperVerticalAngle / Math.PI);
            eqrlayer.biasY = -eqrlayer.scaleY * upperFrac;
```
Seems working fine. For the 180 degrees equirect the centralHorizontalAngle = Math.PI (180 deg), upperVerticalAngle = Math.PI/2, lowerVerticalAngle = -Math.PI/2.
For 360 equirect, all the same but the centralHorizontalAngle = Math.PI * 2.0 (360 deg).
Now it makes sense! Thanks, @casseveritt!
