### ISSUE TITLE
Depth testing across layers

### ISSUE THREAD

**Issue by avaer** [immersive-web/layers#135]
The explainer mentions depth testing is not to be performed across layers. What is the reasoning behind that? Is it because the platforms targeted currently do not support depth buffers for projection layers?

Also, could it be allowed as an optional feature now or in the future?

**Comment by cabanier** [comment]
> The explainer mentions depth testing is not to be performed across layers. What is the reasoning behind that? Is it because the platforms targeted currently do not support depth buffers for projection layers?

The depth buffers are only supported to do reprojection.  They aren't used to "sort" pixels between layers. 

> Also, could it be allowed as an optional feature now or in the future?

Do you know of any runtime that allow this? Would you expect this sorting to also take the other layers into account?

**Comment by avaer** [comment]
Yes, the Exokit runtime utilizes WebXR layers for per pixel depth sorting, as a traditional depth test. It does depend on the order of layers due to transparency.

As far as I could tell the [OpenXR depth extension](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_composition_layer_depth) does not preclude this usage, and folks at PlutoVR and Monado are experimenting with it as a feature.

It would be good if WebXR was in alignment.

**Comment by cabanier** [comment]
> As far as I could tell the [OpenXR depth extension](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_composition_layer_depth) does not preclude this usage, and folks at PlutoVR and Monado are experimenting with it as a feature (I could be wrong on this point, I'll ask them to chime in on this issue).

Yes, it would be good to know if they are working on a hardware compositor that supports this and if so, how it works

> It would be good if WebXR was in alignment either way.

I agree.

**Comment by cabanier** [comment]
> As far as I could tell the [OpenXR depth extension](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_composition_layer_depth) does not preclude this usage

hmm, actually it does:

> The XR runtime may use this information to perform more accurate reprojections taking depth into account.

It doesn't say anything about depth sorting between layers

**Comment by avaer** [comment]
> Yes, it would be good to know if they are working on a hardware compositor that supports this and if so, how it works

I don't think it's a hardware compositor, but driver software.

> It doesn't say anything about depth sorting between layers

It doesn't specify the manner of the reprojection, nor does it SHOULD NOT any particular mode so it is definitively not precluding (making impossible) anything. Arguably, sorting the layers provides the most accurate reprojection of the layer, so using it for sorting falls into both text and spirit of the MAY.

**Comment by bradgrantham-lunarg** [comment]
Reprojection is the warping of a single composition layer to better match the viewer's head orientation at the time of scanout.  Putting together multiple layers into an image is composition.  So if the spec says `The XR runtime may use this information to perform more accurate reprojections taking depth into account`, it means that the information may or may not be used to warp the single layer better.

I think there's probably a place for a "depth-aware" composition extension.

**Comment by cabanier** [comment]
@avaer I will close this issue for now. Please let me know if there's a UA that wants to implement this.

**Comment by avaer** [comment]
We mentioned Exokit already, I'm not sure why the main usage of WebXR layers is ignored.

I'll ping the others again.

**Comment by cabanier** [comment]
@avaer Can you create a PR and put it on the agenda so we can discuss?

**Comment by avaer** [comment]
Yes, I can do that, though I have a conflict for [tomorrow's teleconference](https://github.com/immersive-web/administrivia/blob/master/meetings/wg/2020-05-12-Immersive_Web_Working_Group_Teleconference-agenda.md).

Did you want to move it to next week or still discuss it tomorrow?

**Comment by cabanier** [comment]
If you can't make it, let's move it to the next CG call in 2 weeks (unless @AdaRoseCannon can cover it in the WG call next week). 
Once you create the PR, we can begin the discussion here.

**Comment by thetuvix** [comment]
OpenXR does preclude use of depth data to affect sorting of pixels between layers.

[Section 10.4.2 of the OpenXR 1.0 specification](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#compositing) mentions the following:
> Composition layers **must** be drawn in the same order as they are specified in via XrFrameEndInfo, with the 0th layer drawn first. Layers **must** be drawn with a "painter’s algorithm," with each successive layer potentially overwriting the destination layers whether or not the new layers are virtually closer to the viewer.

Nothing specified in the `XR_KHR_composition_layer_depth` extension modifies that provision.  To ensure consistency between OpenXR runtimes, there are conformance tests that ensure that painters' algorithm is upheld here.

We have discussed further OpenXR extensions that would allow runtimes to offer apps to opt in to enable per-pixel depth tests between compositor layers.  However, no OpenXR runtimes currently support that capability.  I could imagine an equivalent WebXR module that offers that opt-in.

**Comment by cabanier** [comment]
> We have discussed further OpenXR extensions that would allow runtimes to offer apps to opt in to enable per-pixel depth tests between compositor layers. However, no OpenXR runtimes currently support that capability. 

Do you know of any timelins of when this feature would be supported?

> I could imagine an equivalent WebXR module that offers that opt-in.

Depending if @avaer agrees, we can put it in the next level of the layers spec.
I just wonder how exokit could implement this without platform support.

**Comment by avaer** [comment]
Thanks for sharing that @thetuvix! That would appear to be a good reason for WebXR to match by default.

Would still be interested in the per-pixel depth test as a WebXR module; will add that to the CG call agenda when interested parties are intent on joining.

**Comment by avaer** [comment]
> I just wonder how exokit could implement this without platform support.

We don't go down to the platform for layers; it is in a virtualized compositor.

**Comment by thetuvix** [comment]
> Do you know of any timelines of when this feature would be supported?

Not yet.  As discussed here, it would involve support in the underlying compositors that power each vendor's runtime.  At the moment, most OpenXR implementers are currently more focused on [defining and implementing the set of extensions that will reach achieve full feature parity for our devices](https://docs.microsoft.com/en-us/windows/mixed-reality/openxr#roadmap).

**Comment by cabanier** [comment]
We're thinking off adding this feature to the platform because it solves some of the drawbacks of having depth separation between the layers. It seems that on the specification side, it could just be a feature that is requested a session creation time.

/agenda Discuss interest in depth sorting between layers

**Comment by cabanier** [comment]
/tpac discuss limitations of depth testing across layers

**Comment by cabanier** [comment]
#271 implements option 1
