### ISSUE TITLE
Clarify behaviour that is expected to happen every frame?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#141]
At the moment, the layers spec has implicit state that is updated every frame, in particular https://immersive-web.github.io/layers/#xrwebglsubimagetype says "The colorTexture and depthStencilTexture objects MUST only be used during the XR animation frame of the current session and MUST be made invalid once the XR animation frame completes."

Should we make explicit what state updates are expected every frame? Should we use fame updates (https://immersive-web.github.io/webxr/#frame-update) to do so?

**Comment by asajeffrey** [comment]
related to #101

**Comment by Manishearth** [comment]
The frame update does not allow for the behavior where the attributes are "invalid" outside of the frame, in fact we do not have a concept of "inside the frame" right now.

Perhaps these should be methods that take in an (active-only) `XRFrame`?

**Comment by cabanier** [comment]
> related to #101

Yes, this language needs to be changed. I'm waiting for feedback from the WebGL group on how we can rephrase the texture lifetime.

**Comment by cabanier** [comment]
> Should we make explicit what state updates are expected every frame? Should we use fame updates (https://immersive-web.github.io/webxr/#frame-update) to do so?

Are you just talking about state of the textures or also about state of the whole system (ie layer attributes, layers array, etc)?

**Comment by asajeffrey** [comment]
> Are you just talking about state of the textures or also about state of the whole system (ie layer attributes, layers array, etc)?

Well, the thing that got me started thinking about this is textures, but there may be other bits of state that we have to update every frame.

**Comment by asajeffrey** [comment]
Slightly annoyingly, frame updates only get applied at the beginning of a rAF, AFAICT there's no matching hook for the end of an rAF, which we might need for texture invalidation.

**Comment by cabanier** [comment]
> Well, the thing that got me started thinking about this is textures, but there may be other bits of state that we have to update every frame.

There's [language in the spec](https://immersive-web.github.io/layers/#updaterenderstatechanges) that deals the state change of the layers array.
There's an open question on how layer attribute are applied. This is still pending with the PR #134 . I changed the layer attributes to read-only and made it so you have to set them through a dictionary which is applied later. However, this is very awkward.
Maybe the attributes should stay read/write and be applied at the end of the xrframe.

**Comment by asajeffrey** [comment]
Oh yes, the changes that happen when the render state is updated are fine, it's the per-frame state updates that are worrying me.

**Comment by cabanier** [comment]
@asajeffrey since this is already coverd by 2 other issues, should we close this one? I'm worried it might get confusing otherwise.

**Comment by asajeffrey** [comment]
OK, we can move the discussion to #101.
