### ISSUE TITLE
Depth testing across layers

### ISSUE THREAD

**Issue by avaer** [immersive-web/layers#142]
For context, the Exokit UA has been the main consumer of WebXR layers functionality for the last few years (that's predating this spec proposal, but we're glad the experiment is being standardized).

Our main use case is using layers for composition of the depth buffer in the multi-app case.

The explainer mentions depth testing is not to be performed across layers. What is the reasoning behind that? Is it because the platforms targeted currently do not support depth buffers for projection layers?

Also, could it be allowed as an optional feature now or in the future?

Continuation of https://github.com/immersive-web/layers/issues/135

**Comment by avaer** [comment]
Closing because https://github.com/immersive-web/layers/issues/135 is re-opened, thanks @rcabanier !

**Comment by cabanier** [comment]
I reopened #135 so we can continue there.
Can you create a PR and put it on the agenda so we can discuss it?
