### ISSUE TITLE
Bring the layers spec into the Working Group

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#148]
We've been making good progress on the specification and the implementation of WebXR layers.

Do people agree that it is ready to move to the Working Group so we can produce the First Public Working Draft?

**Comment by cabanier** [comment]
/agenda Can the layers spec move to the WG? Can we produce the FPWD?

**Comment by AdaRoseCannon** [comment]
In preparation for moving to the WG please could what is currently the README be moved to an `explainer.md` and then the README be similar to the other WG one like [the one in hit-test](https://github.com/immersive-web/hit-test/blob/master/README.md)

**Comment by cabanier** [comment]
Layers was moved to the WG :-)
