### ISSUE TITLE
Specify that all WebGL contexts which have XR layers are flushed at the end of the frame

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#151]
https://immersive-web.github.io/webxr/#opaque-framebuffer says

> Before the opaque framebuffer is presented to the immersive XR device the user agent shall ensure that all rendering operations have been flushed to the opaque framebuffer.

There's no matching text for layers, should it say something like "Before each layer is presented to the immersive XR device the user agent shall ensure that the layer's rendering context has been flushed"?

I think we want to say that the context has been flushed, since `gl.flush()` is a method on the rendering context, not a texture or framebuffer?

**Comment by cabanier** [comment]
I agree. I will add some text to the spec to say that all rendering operations must be flushed before a layer should be presented.
