### ISSUE TITLE
Projection layer helperInit viewPixelWidth and Height

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#153]
https://immersive-web.github.io/layers/#dom-xrwebglbinding-createprojectionlayer says

> Let bufferSize be the recommended WebGL framebuffer resolution multiplied by init’s scaleFactor.

and 

> Initialize helperInit’s viewPixelWidth to bufferSize width.
> Initialize helperInit’s viewPixelHeight to bufferSize height.

but https://immersive-web.github.io/webxr/#recommended-webgl-framebuffer-resolution is the size of the whole framebuffer, not just the size of one view, whereas https://immersive-web.github.io/layers/#allocate-color-textures uses `viewWidth` and `viewHeight` as the size of one view, not the whole texture,

For example, on a stereo device which prefers stereo L-R, where each eye display is WxH pixels, the recommended framebuffer resolution will be 2WxH, so `helperInit` will have `viewPixelWidth` of 2W rather than W.

**Comment by asajeffrey** [comment]
This may need a fix to the webxr spec, as AFAICT it doesn't provide a way to get the resolution of each view, just the resolution of the whole framebuffer.

**Comment by cabanier** [comment]
Could it be as simple as fixing the following line:

> Let bufferSize be the recommended WebGL framebuffer resolution multiplied by init’s scaleFactor divided by the number of all the session’s XRViews.

**Comment by asajeffrey** [comment]
But that divides both the width and height. I think we need some way for the device to indicate its preferred view resolution (in the way it can specify its preferred framebuffer resolution).
