### ISSUE TITLE
Presenting stereo layers to devices with more than two views

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#155]
https://immersive-web.github.io/layers/#xrcompositorchanges discusses how to present stereo layers when there's only one view, but not when there's more than two (e.g. devices which record to a third view).

**Comment by asajeffrey** [comment]
Related to #114

**Comment by asajeffrey** [comment]
Possibly best to leave this up to the UA, as this is likely to vary between devices?

**Comment by cabanier** [comment]
> Possibly best to leave this up to the UA, as this is likely to vary between devices?

I agree. I will add it to the spec.
