### ISSUE TITLE
Allow a layer layout which puts all the views in one texture?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#156]
Currently when textures are allocated for layers in https://immersive-web.github.io/layers/#allocate-color-textures and https://immersive-web.github.io/layers/#allocate-color-textures the only layout which allocates textures for all the views of a device is `default`, which allocates a texture per view (when the texture type is `texture`). So if a content provider wants to use one texture for all the views, they have to use a `XRWebGLLayer` and an opaque framebuffer.

**Comment by asajeffrey** [comment]
One side-effect of this is that we can't implement `XRWebGLLayer` as a polfill on top of XR layers, since there's no appropriate layout. In the case of mono devices we can use `mono`, and for stereo we can use `stereo-left-right`, but there's no layout for devices with more than two views other than `default`.

**Comment by asajeffrey** [comment]
Also, in https://immersive-web.github.io/layers/#determine-the-layout-attribute, we allow a device to prefer `stereo-left-right` or `stereo-top-bottom`, but these only make sense for devices with two views.

**Comment by cabanier** [comment]
> Also, in https://immersive-web.github.io/layers/#determine-the-layout-attribute, we allow a device to prefer `stereo-left-right` or `stereo-top-bottom`, but these only make sense for devices with two views.

That should be addressed with PR #157

**Comment by cabanier** [comment]
> Also, in https://immersive-web.github.io/layers/#determine-the-layout-attribute, we allow a device to prefer `stereo-left-right` or `stereo-top-bottom`, but these only make sense for devices with two views.

That is correct. If a user agent wants to render to a device with 1, 3 or more views, it shouldn't pick  `stereo-left-right` or `stereo-top-bottom`.

**Comment by cabanier** [comment]
>  So if a content provider wants to use one texture for all the views, they have to use a `XRWebGLLayer` and an opaque framebuffer.

I assume it's only the `XRProjectionLayer` that would require this feature? I'm not opposed to extend it to allow this but it was my impression that we wanted to move away from the single texture approach in favor of texture arrays.

**Comment by asajeffrey** [comment]
> That is correct. If a user agent wants to render to a device with 1, 3 or more views, it shouldn't pick `stereo-left-right` or `stereo-top-bottom`.

Yes, but rn they're out of luck if they want to prefer (e.g.) left-right but have more than two displays. This seems like an odd limitation, but I'm not entirely sure what the motivation is for allowing devices to prefer stereo-l-r or -t-b.

**Comment by asajeffrey** [comment]
> I assume it's only the `XRProjectionLayer` that would require this feature? I'm not opposed to extend it to allow this but it was my impression that we wanted to move away from the single texture approach in favor of texture arrays.

Yes, but I'm hoping we can impolement `XRWebGLLayer` using projection layers, which I think we can for stereo devices, but not for devices with more than two views.

**Comment by cabanier** [comment]
> Yes, but I'm hoping we can impolement `XRWebGLLayer` using projection layers, which I think we can for stereo devices, but not for devices with more than two views.

With a polyfill or under the hood in C++ as a simplification?

**Comment by asajeffrey** [comment]
> With a polyfill or under the hood in C++ as a simplification?

I'm doing it under the hood, but it would be nice if could be as a JS polyfill too.

**Comment by cabanier** [comment]
I don't quite understand what the use case is for a polyfill. Can you elaborate?

**Comment by asajeffrey** [comment]
I guess it depends on whether we think projection layers are complementing `XRWebGLLayer` or replacing it. If it's a replacement, then we should make sure that we've not lost functionality, and the easiest way to do that is to write a polyfill.

**Comment by cabanier** [comment]
Projection layers are complementing `XRWebGLLayer'. This is why we allow `XRWebGLLayer' in the `layers` array.

**Comment by asajeffrey** [comment]
Sure, we can close this issue.
