### ISSUE TITLE
Should layer support be requested at session creation time?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#16]
The current proposal doesn't specify if there are limits when an author can use layers.
This implies that a session can switch from a regular WebXR session to one that uses layers and vice versa.

Is this something that we want to support? I can see that this would be difficult to implement so it would be nice to avoid.

**Comment by cabanier** [comment]
/agenda Should layer support be requested at session creation time?

**Comment by toji** [comment]
I don't think it's a terrible idea to have a "layers" feature descriptor, especially because some platforms may not support it at all and if your experience depends on layers making it a required feature would give you a way of communicating that the feature is missing early on.

**Comment by mounirlamouri** [comment]
For future references, wouldn't be better to try to have the discussion on GitHub first and use the call if we can't find a solution quickly? It seems that this is fairly uncontroversial as all features so far have a feature descriptor and we should probably just do the same for layers unless we have a reason to.

**Comment by cabanier** [comment]
During a conversation some people has a strong opinion that this should not be a feature descriptor. You, @toji and I seem to be in agreement that it should be but it would be good to have a group decision on this.

**Comment by AdaRoseCannon** [comment]
Postponed issue until next weeks call since.

**Comment by cabanier** [comment]
During today's call we decided to not request layer support and just rely on the author doing feature detection.
We might revisit this if the IDL or the implementation become too complicated

**Comment by mounirlamouri** [comment]
Can you please explain why?

**Comment by cabanier** [comment]
@Artyom17 and @toji were thinking that we could support both classic WebXR and layers at the same time. An author that wanted to use layers could request a normal session and then feature detect the layer API.

@Manishearth expressed some concerns since this could do weird things with the layers array and I thought that this might make the implementation and the spec more difficult since an author can now switch between classic and layers at will.

**Comment by Manishearth** [comment]
> @Manishearth expressed some concerns since this could do weird things with the layers array and I thought that this might make the implementation and the spec more difficult since an author can now switch between classic and layers at will.

My concern is only around the case where the base layer can be accessed via `session.baseLayer` _and_ `session.layers[0]`. If we spec it as being not a member of that array we should be fine.
