### ISSUE TITLE
Should non-projection layers support more than 2 views?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#163]
It seems only mono and stereo view should be supported

**Comment by cabanier** [comment]
/agenda Should non-projection layers support more than 2 views?

**Comment by cabanier** [comment]
While rewording `getViewSubImage` to account for devices with multiple views, I realized that the concept of `view` doesn't really apply to non-projection layers.
They don't fill the views of the XR Device and they are only reasonable to be mono or stereo.

Maybe we should change `getViewSubImage` to `getSubImageForLayout` for non-projection layers which takes an `XREye` enum instead of an `XRView`.

@toji @Manishearth thoughts? 
I also put this on the agenda for tomorrow

**Comment by Manishearth** [comment]
Maybe I'm misunderstanding why layers need multiple view subimages: this is to render 3D content to them, yes? If you want that content to be properly 3D, shouldn't it be different for each view? How would this work for a CAVE system?

**Comment by cabanier** [comment]
> Maybe I'm misunderstanding why layers need multiple view subimages: this is to render 3D content to them, yes? 

Yes but typically that stereo content is not calculated from the view/projection matrices.

> If you want that content to be properly 3D, shouldn't it be different for each view? 

The content should be different for each eye if it's `stereo` and the same if it's `mono`.
Non-projection layers are 2D surfaces that can are drawn by the compositor in any position. XRWebGLLayer and projection layer that fill the fov/all the views.

> How would this work for a CAVE system?

A layer on a cave system can only show 1 eye at a time. 
The spec should call out that for such devices the XR Compositor should pick one of the textures from the layer and discard the other one.

**Comment by Manishearth** [comment]
> Yes but typically that stereo content is not calculated from the view/projection matrices.

Ah! Hmmm. Won't this result in the "3d" content shifting weirdly as you move around?

> A layer on a cave system can only show 1 eye at a time.

Oh fair, what about observer views?

**Comment by cabanier** [comment]
> > Yes but typically that stereo content is not calculated from the view/projection matrices.
> 
> Ah! Hmmm. Won't this result in the "3d" content shifting weirdly as you move around?

Yes, but it's not as bad as you expect :-)

> > A layer on a cave system can only show 1 eye at a time.
> 
> Oh fair, what about observer views?

Those will get also only get 1 eye. 
There's already [some text for the XR compositor](https://immersive-web.github.io/layers/#xrcompositorchanges) in the spec, but it needs to be rewritten.

**Comment by Manishearth** [comment]
Hmmm. I guess that's fine. An API that takes an XREye makes sense because quad views get easily dealt with as well, with subimage shared between the two views. Should pick some behavior for XREye::None for a primarily-stereo display (probably default to L/R/UA choice)
