### ISSUE TITLE
Language for throwing a NotSupportedException differs between XRWebGLBinding and XRMediaBinding

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#183]
For example, step 2 of https://immersive-web.github.io/layers/#dom-xrwebglbinding-createquadlayer is

> If session was not created with "layers" enabled, throw an NotSupportedError and abort these steps.

but step 2 of https://immersive-web.github.io/layers/#dom-xrmediabinding-createquadlayer is

> If the device does not support the creation of an XRQuadLayer, throw an NotSupportedError and abort these steps.

Should these be unified?

**Comment by cabanier** [comment]
Yes. I will fix.
