### ISSUE TITLE
Should RenderState's layers attribute be marked SameObject?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#185]
In the WebIDL at https://immersive-web.github.io/layers/#xrrenderstatechanges there's
```webidl
 [SameObject] readonly attribute FrozenArray<XRLayer> layers;
```

Should this really be `[SameObject]`? What happens when the render state is updated?

**Comment by cabanier** [comment]
I think so. The array that is return is always the same.

**Comment by asajeffrey** [comment]
But in that case it shouldn't be a `FrozenArray`?

**Comment by cabanier** [comment]
I'm unsure. We definitely don't want to make it mutable on the JS side but I agree it's weird that it can change.

**Comment by asajeffrey** [comment]
I think the easiest thing to do is remove the `[SameObject]` attribute.
