### ISSUE TITLE
Updating the render state with a `null` layers array

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#189]
https://immersive-web.github.io/layers/#updaterenderstatechanges says:

> If newState’s layers is not empty

but the webidl at https://immersive-web.github.io/webxr/#dictdef-xrrenderstateinit says:

```
  sequence<XRLayer>? layers;
```

so it is not obvious what is meant here, in the case that `layers` is `null`.

**Comment by asajeffrey** [comment]
Should the text say "If newState's `layers` is set..."?

**Comment by cabanier** [comment]
Yes, I think that would be the correct behavior.
Also, we need to abort step 1. I will make the change and publish a PR.
