### ISSUE TITLE
XRMediaLayerInit can't be empty

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#191]
https://immersive-web.github.io/layers/#xrmediabindingtype has three uses of `optional XRMediaLayerInit init
 = {}` but at https://immersive-web.github.io/layers/#xrmedialayerinittype there's a field ` required XRSpace space`, so `{}` isn't a valid `init`.

**Comment by cabanier** [comment]
You're right. This is left over when we had a default space. I will update.
