### ISSUE TITLE
XRProjectionLayer layers array behavior when the "layers" feature descriptor is not requested

### ISSUE THREAD

**Issue by MortimerGoro** [immersive-web/layers#193]
I'm implementing WebXR Layers in Firefox Reality and found this part of the spec confusing:
- Layers of type XRProjectionLayer MUST always be supported, regardless if the feature descriptor was requested.
- UpdateRenderState: if the layers array was passed and the session was not created with "layers" enabled, throw a NotSupportedError and abort these steps.

According to both statements the XRProjectionLayers can be created if the "layers" feature is not requested but can't be passed in the UpdateRenderState layers array if the layers feature is not enabled. So they are created for nothing.

We need to make this more clear in the spec. I guess the intended behavior is:  "if the layers array contains any XRLayer that is not a XRProjectionLayer or a XRWebGLLayer and the session was not created with "layers" enabled, throw a NotSupportedError and abort these steps"

**Comment by asajeffrey** [comment]
Another fix would be to add a test to https://immersive-web.github.io/layers/#dom-xrwebglbinding-createprojectionlayer that throws a `NotSupportedException` if the session was created without `layers` enabled and `textureType` is not `texture`.

**Comment by cabanier** [comment]
Yes. That was an oversight. I will fix this in the spec.
If `baselayer` is null, layers can have entries and vice versa.

**Comment by cabanier** [comment]
@MortimerGoro I'm excited to hear that Firefox Reality is adding support!
Is that different from what @asajeffrey is working on?

Please let me know if you find any other problems in the spec.

**Comment by MortimerGoro** [comment]
@cabanier yes, it's a different implementation. It's a long story, but Mozilla has two browser engines that are used in VR projects: Servo and Gecko/Firefox. I'm working on the Gecko implementation, which is the one used for Firefox Reality shipped on Oculus Quest/Go devices.

The spec looks good so far. I haven't read all the discussions, maybe it has been already commented: on a high level the only thing I miss would be a separation between a layer and the surface/texture (as OculusVR/OpenXR do with SwapChains). But that separation might not be a friendly web pattern. Example of a use case: In Firefox Reality frontend we used that separation to dynamically switch between a flat (Quad Layer) and curved (Cylinder Layer) window without recreating or painting to a different surface, so the switch is super fast. With WebXR Layers you would need to render to different textures.

**Comment by cabanier** [comment]
>  I haven't read all the discussions, maybe it has been already commented: on a high level the only thing I miss would be a separation between a layer and the surface/texture (as OculusVR/OpenXR do with SwapChains). But that separation might not be a friendly web pattern. Example of a use case: In the Firefox Reality frontend we used that separation to dynamically switch between a flat (Quad Layer) and curved (Cylinder Layer) window without recreating or painting to a different surface, so the switch is super fast. With WebXR Layers you would need to render to different textures. I can file a new issue if this hasn't been already commented

Yes, we discussed this at the very beginning.
As you inferred, we tried to hide the concept of a swapchain because it would be very hard to spec and would need extensive changes in WebGL. Regular WebXR also doesn't expose it.
You're right that this stops an implementation from quickly changing between layer types. Do you strongly feel that this should be in the first version of the Layers spec? AFAIK we don't commonly change layer types on the Oculus platform (but I can investigate).

**Comment by cabanier** [comment]
Closing issue since this was resolved with pr #194
