### ISSUE TITLE
Spec link for "invalid" texture

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#195]
In https://immersive-web.github.io/layers/#xrwebglsubimagetype there's "The colorTexture and depthStencilTexture objects MUST only be used during the XR animation frame of the current session and MUST be made invalid once the XR animation frame completes." but no spec link for "invalid".

I suspect what this means is "set the invalidated flag" (https://www.khronos.org/registry/webgl/specs/latest/1.0/#webgl-object-invalidated-flag).

**Comment by asajeffrey** [comment]
This does beg the question of when the flag is unset. Is it at the beginning of each rAF?

**Comment by asajeffrey** [comment]
Related to #174

**Comment by cabanier** [comment]
This was mentioned in https://github.com/immersive-web/layers/issues/174#issuecomment-650474042
`getSubImage` / `ViewSubImage` make the texture valid again.

**Comment by asajeffrey** [comment]
And that unsets the `invalid` flag for just the textures returned by `get*SubImage`?

**Comment by cabanier** [comment]
Yes. For instance, if the layer is not updated during a rAF call, there is no need to pull a texture from the swapchain.
