### ISSUE TITLE
Is a framebuffer with an invalid attachment invalid or incomplete?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#196]
Outside an rAF, the webgl textures associated with a layer are invalid (https://immersive-web.github.io/layers/#xrwebglsubimagetype). If such a texture is attached to a framebuffer, then what is its state outside an rAF? Also invalid? Or incomplete? Or...?

**Comment by asajeffrey** [comment]
Related to #195 and #174.

**Comment by cabanier** [comment]
> Related to #195 and #174.

Yes, this is related to #174.
I believe the consensus was that those texture should be detached at frame end.

**Comment by asajeffrey** [comment]
And it's the content's responsibility to reattach them at the next rAF?

**Comment by cabanier** [comment]
> And it's the content's responsibility to reattach them at the next rAF?

Yes

**Comment by asajeffrey** [comment]
Okay, what about if the texture is bound with `gl.bindTexture`?

**Comment by cabanier** [comment]
I believe so.
Do you want to take a stab at writing down the behavior? We could also work on it together.

**Comment by asajeffrey** [comment]
Can do.

**Comment by asajeffrey** [comment]
Unsurprisingly, the recent announcements from Mozilla have derailed this. I will probably have a bit more free time in a bit, but right now I'm afraid I'm running round like a headless chicken.
