### ISSUE TITLE
More general layer quality hints. (AKA: Enabling Oculus Go-style fixed foveation)

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#2]
Currently today we have one hint that can be supplied to an `XRWebGLLayer` after it's creation to adjust performance: The viewport size for each view can be adjusted using `requestViewportScaling()`. As the name implies, this is only a request and the system is free to ignore, clamp, or otherwise tweak the requested values.

This pattern seems like it could be made more general, and in doing so provide some overall guidance for ways that vendors can safely experiment with similar features that may not be supported everywhere. A concrete example is the [fixed foveation technique](https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-ffr/) used by the Oculus Go (and enabled via OpenGL extensions on similar hardware).  This is a feature which could probably be safely turned on by default at it's lowest level with close to no visual impact and a minor performance boost, but developers can get more out of it by intentionally opting-in to higher levels of foveation knowing that there's a quality/performance tradeoff being made that will only be appropriate for certain kinds of content.

Ideally we'd like to allow browser/hardware vendors to enable developers to make that tradeoff while having as little impact on the API surface as possible and clearly communicating that invoking the functionality is a hint to the system, not a guarantee. To that end, I'd propose the following API change:

```webidl
dictionary XRWebGLLayerHints {
  double viewportScale = 1.0;
  // In the near future: XRFoveationLevel foveatedRendering = "low"; ?
};

partial interface XRWebGLLayer {
 // Remove requestViewportScaling();
  void setLayerHints(XRWebGLLayerHints hints);
};
```

Which would turn the current viewport scaling logic into:

```js
xrLayer.setLayerHints({ viewportScale: 0.75 });
```

The benefit here is that we've now established a clear place for these kinds of hints to happen, in a form that allows vendors to experiment with hardware-specific features without disrupting the core API much. Taking that notion further, we may want to institute a pattern in the spec that anything which is not guaranteed to take effect is appropriately labeled as a "hint". (For example, maybe `framebufferScaleFactor` is better described as `framebufferScaleHint` since we know that systems like Windows Mixed Reality can't honor it.)

I'm curious what the other CG members think of this approach, and also if there are features that you would have in mind to apply such a system to (or, perhaps more importantly, features that this model doesn't accommodate well.)

**Comment by cabanier** [comment]
@toji should this issue be in the layers repo? It seems like a general WebXR issue bit it will also apply to layers

**Comment by toji** [comment]
Yeah, I think this can safely move to layers. I'll transfer it.

**Comment by cabanier** [comment]
#112 will address this.
