### ISSUE TITLE
How to mark layers as dirty?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#20]
Non-projection layers don't have to be updated at the device's refresh rate.
What is the best way to indicate if a layer needs to be updated after a Raf?

**Comment by avaer** [comment]
Does it need to be indicated or can the graphics layer track what is dirty?

**Comment by cabanier** [comment]
It would be cleaner if the author explicitly marks it as such.
Another way would be to mark it dirty if the author calls `getViewSubImage` or `getSubImage` for the layer.

**Comment by klausw** [comment]
FYI, Chrome's WebXR implementation already supports applications that don't update XRWebGLLayer at the device refresh rate. It tracks if the layer is modified during an animation frame using an automatic dirty check for the GL framebuffer, and if it wasn't modified it reprojects the most recent content instead.

I couldn't find a reference to this behavior in the WebXR spec, though the explainer mentions this in the last paragraph of https://github.com/immersive-web/webxr/blob/master/explainer.md#main-render-loop .

**Comment by cabanier** [comment]
I don't believe that is spec compliant. If an application doesn't draw to the framebuffer, it should display as black.
This is why we set `preserveDrawingBuffer` always to false; we didn't want to have to remember the previous buffer.

**Comment by cabanier** [comment]
/agenda clarification is needed on what happens when nothing is drawn to the buffer during a Raf

**Comment by AdaRoseCannon** [comment]
I don't think we got around to discussing this if i recall correctly.

**Comment by cabanier** [comment]
It would be good to get clarification on this. The spec should at least say what needs to happen. 

We didn't expect this behavior and it triggered failures when some sites didn't update in each raf call

**Comment by toji** [comment]
In Chrome, we track whether or not any draw commands are excecuted when the `XRWebGLLayer`'s `framebuffer` is bound, and use that to flip the "dirty" bit. If the rAF callbacks are executed but the dirty bit isn't flipped we allow the last frame to reproject. This was intentional, as it allows for some reasonable behavior during splash screens and loading dialogs where you can allow the hardware to reproject while your page is busy doing other work.

For the layers API I definitely wouldn't mind this being a more explicit mechanism (and easier to track). I was thinking that any calls to `getSubImage()/getViewSubImage()` could be the thing that flags the textures they contain as "dirty", since there's no reason to get the image that I can think of unless you intend to render to it.

**Comment by toji** [comment]
As mentioned on today's call, the WebGL spec does specify the behavior for when the canvas is considered dirty, which I think the WebXR spec should re-use almost exactly (which is Chrome's current behavior. The text is found in the section [2.2 The Drawing Buffer](https://www.khronos.org/registry/webgl/specs/latest/1.0/#2.2)

> WebGL presents its drawing buffer to the HTML page compositor immediately before a compositing operation, but only if at least one of the following has occurred since the previous compositing operation:
>
>  - Context creation
>  - Canvas resize
>  - _clear_, _drawArrays_, or _drawElements_ has been called while the drawing buffer is the currently bound framebuffer

**Comment by jdashg** [comment]
Yeah, there are some corner cases too. (e,g, drawing with ColorMask(0) doesn't dirty) Anything that might alter the the color backbuffer counts, basically. `blitFramebuffer` isn't mentioned in that WebGL 1 spec, but it counts too.

**Comment by jdashg** [comment]
Worth mentioning, but things like drawArrays(0) however do count as dirtying, iirc.

**Comment by toji** [comment]
Also, for completeness: some extensions add new draw commands (like `drawArraysInstancedANGLE`) which count as dirtying.

**Comment by cabanier** [comment]
I opened a new issue in the WebXR repo. I will close this one since we have a solution for layers.
