### ISSUE TITLE
Publish first Working draft of the layers spec

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#202]
/agenda The layers spec hasn't changed much in a while and implementation in the Oculus browser is proceeding. Can we publish a WD?

**Comment by cabanier** [comment]
#201 should be submitted before WD.

**Comment by himorin** [comment]
@Yonet have we processed call for consensus in the IWWG on this??
https://www.w3.org/2020/09/15-immersive-web-minutes.html#t03
CG call minutes say no objection, but could not find pointer(s) in the WG.

**Comment by cabanier** [comment]
Are you saying that it doesn't count because it was a CG call?
If so, we should do it in the next WG call.

**Comment by himorin** [comment]
per our WG charter, we need to open formal CfC
https://www.w3.org/2020/05/immersive-Web-wg-charter.html#decisions

> To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A call for consensus (CfC) will be issued for all resolutions (for example, via email and/or web-based survey), with a response period from one week to 10 working days, depending on the chair's evaluation of the group consensus on the issue. If no objections are raised on the mailing list by the end of the response period, the resolution will be considered to have consensus as a resolution of the Working Group.

**Comment by cabanier** [comment]
OK. How can I do that?

**Comment by AdaRoseCannon** [comment]
I'll do it now.

**Comment by AdaRoseCannon** [comment]
Sent out.

**Comment by cabanier** [comment]
Thanks @AdaRoseCannon !

**Comment by himorin** [comment]
Thank you so much for catching this @AdaRoseCannon ! (will take care for following procedure in transitions repo)
