### ISSUE TITLE
Consider moving/replacing alpha, depth, and stencil options

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#213]
This came up while [discussing WebGPU integration](https://github.com/immersive-web/proposals/issues/58) with the Layers API.

With WebGPU it would be ideal to allow the texture formats of the layer's underlying swap chain to be specified directly, probably from a list of compatible formats given by the API.

For example (not final API shape): 

```js
// Supported formats are reported in order of preference
const layerTextureDescriptor = {
  colorFormat: gpuBinding.supportedColorFormats[0], // Example: 'rgba8unorm'
  depthStencilFormat:  gpuBinding.supportedDepthStencilFormats[0], // Example: 'depth24plus'
};

const projectionLayer = gpuBinding.createProjectionLayer(layerTextureDescriptor, { /* XRProjectionLayerInit */ });
```

The primary thing to note here is that `colorFormat` will explicitly specify whether or not an alpha channel is part of the format, so the `alpha` value in `XRProjectionLayerInit` now must be ignored. Similarly, the `depthStencilFormat`, if specified, takes the place of the `depth` and `stencil` attributes of the `XRProjectionLayerInit`. The same goes for every other Layer type.

It seems really unfortunate to leave values in the dictionary that this variant of the Layers will ignore. The way I see it there's a couple ways that we could approach resolving that:

**1. Leave the base Layers API as-is.**
The WebGPU variant will likely create its own `____LayerInit` dictionaries and fold the format options into it. For example:

```webidl
dictionary XRGPUProjectionLayerInit {
  required GPUTextureFormat colorFormat;
  GPUTextureFormat? depthStencilFormat;
  GPUTextureUsageFlags textureUsage = 0x10; // GPUTextureUsage.OUTPUT_ATTACHMENT
  double scaleFactor = 1.0;
};
```

This results in some otherwise avoidable code duplication, but has the least amount of impact on the current Layers API.

**2. Move WebGL-specific options to a separate dictionary.**
This would break backwards compat (fortunately the API hasn't fully shipped), but result in a more consistent interface between graphics APIs. It should be noted that WebGPU will likely not require specifying a `XRTextureType`, so that can be counted as part of the WebGL options. For example:

```webidl
dictionary XRWebGLLayerTextureInit {
  required XRTextureType textureType;
  boolean depth = true;
  boolean stencil = false;
  boolean alpha = true;
};
```

Which in use would look like:

```js
const glProjectionLayer = glBinding.createProjectionLayer(
  { textureType: 'texture-array', alpha: false },
  { scaleFactor: 0.9 }
);
```

You could even break from WebGL's established framebuffer pattern and let WebGL formats be specified directly like with WebGPU, since we're not dealing with opaque framebuffers anymore. That would require the binding to advertise a list of supported formats, and may not be worth the trouble, but it's worth considering.

Thoughts? The WebGPU interface is still in flux, so I'm open to discussing any and all options regarding how to make the interface between both graphics APIs as clear as we can.

**Comment by cabanier** [comment]
> It seems really unfortunate to leave values in the dictionary that this variant of the Layers will ignore

I agree. The spec should not have functions that take parameters which are then partially ignored.

> The way I see it there's a couple ways that we could approach resolving that:
> 1. Leave the base Layers API as-is.
> 2. Move WebGL-specific options to a separate dictionary.

I thought about this and I leaning towards option 1.
Even though separating the options into separate dictionaries makes sense, for authors it may seem a bit random why an option goes to one dictionary and not the other. Also, having to provide 2 dictionaries is slightly more inconvenient.

**Comment by toji** [comment]
That's reasonable. Since dictionaries can be extended maybe we want to leave the base layer options in the dictionaries we have now and then layer the API-specific options on top of them?

```webidl
// From memory, may be off in dumb ways.
dictionary XRWebGLProjectionLayerInit : XRProjectionLayerInit {
  boolean alpha = true;
  boolean depth = true;
  boolean stencil = false;
  required XRTextureType textureType;
}
```

**Comment by cabanier** [comment]
I think that sounds great.
Should we keep this in the back of our mind, or should I start making those changes? 

Since this won't change how authors interact with the Layers API, it seems that it can wait.

**Comment by toji** [comment]
The only thing it would currently change in practice is you wanted to move the textureType into the dictionary.

Regardless, though, we should probably make the change in the spec now so that the GPU layers can logically build off of it. Implementations won't have to change right away, since dictionary types are non-observable.

**Comment by cabanier** [comment]
I don't remember why we didn't make the texture type part of the dictionary. It feels a bit odd that it sits outside the dictionary.

**Comment by toji** [comment]
IIRC it was one of a couple of values that were passed in that way initially, and then we gradually moved everything else into the dictionary over time except that. I wouldn't mind it being part of the dictionary now. For that matter, it might be nice to give it a default value too (probably `texture`).

**Comment by cabanier** [comment]
OK. I will move it to a single dictionary and we'll update our code to match it.
