### ISSUE TITLE
WebGL 1 does not support depth textures without an extension.

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#223]
Kind of embarrassed I came to this realization so late, but in WebGL 1 we can't return depth textures unless the developer has enabled the [WEBGL_depth_texture](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/) extension. (WebGL 2 has depth texture support out of the box.)

It seems fine to say that if the WebGL extension has been activated by the developer then the XR layers should be able to use it. Previously we discussed how to handle cases where required extensions aren't present in the context of the lighting API, and the general consensus was that we shouldn't activate them behind the developers back or try to pretend that they're not available but return resources that use them regardless. (I'll see if I can dig up the actual conversation and link it here.) So that would imply that we either need to have a path for WebGL 1 that doesn't require allowing depth textures (while preferably allowing them when enabled) or take a more drastic step like restricting the layers API to WebGL 2 only, which we've previously gone out of our way to avoid.

My first impression would be to change the defaults for layer creation to not include a depth/stencil texture, and then fail layer creation if a depth texture is explicitly requested but the required extension/API level is not enabled.

Other alternatives that come to mind would be to remove the option for having the API provide depth textures entirely (at least for now) or have an option for returning depth renderbuffers (which seems unnecessarily complicated).

I'd also suggest that if we're leaning towards any paths that increase the need for developers to create their own depth buffers we should maybe take a look at making it easier for them to create compatible buffers (such as reporting the color texture width/height outside of the frame loop)

**Comment by cabanier** [comment]
> Kind of embarrassed I came to this realization so late, but in WebGL 1 we can't return depth textures unless the developer has enabled the [WEBGL_depth_texture](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/) extension. (WebGL 2 has depth texture support out of the box.)

The spec already is designed to handle this.
See step 5 of the [allocate depth textures for projection layers](https://immersive-web.github.io/layers/#allocate-depth-textures-for-projection-layers) algorithm.

> ...Previously we discussed how to handle cases where required extensions aren't present in the context of the lighting API, and the general consensus was that we shouldn't activate them behind the developers back or try to pretend that they're not available but return resources that use them regardless.

I agree.
> So that would imply that we either need to have a path for WebGL 1 that doesn't require allowing depth textures (while preferably allowing them when enabled) or take a more drastic step like restricting the layers API to WebGL 2 only, which we've previously gone out of our way to avoid.

Right now, you will be unable to create a layer that creates a depthStencil texture in WebGL1 unless the extension was enabled. We discussed this in the past on (github)[https://github.com/immersive-web/layers/issues/35] and a weekly call.

> I'd also suggest that if we're leaning towards any paths that increase the need for developers to create their own depth buffers we should maybe take a look at making it easier for them to create compatible buffers (such as reporting the color texture width/height outside of the frame loop)

I'm not following. Are you saying that we need to make it easier for authors to see if depth support is enabled?
FYI The author can already get the width and height of the texture outside of the frame loop.

**Comment by toji** [comment]
I apologize that I didn't see the relevant text in the spec when posting this. Seems that mostly addresses the issues I brought up. I will say that if feels like it may be a good idea to not request depth/stencil buffers by default? That way the default settings work for everyone and if you only have to meet the higher requirements if you explicitly opt in to a depth buffer.

> I'm not following. Are you saying that we need to make it easier for authors to see if depth support is enabled?

No, I think the existing pattern we have for that is fine.

> FYI The author can already get the width and height of the texture outside of the frame loop.

How? For non-projection layers you could infer it from the layer creation args, but otherwise the only time we explicitly report the image width/height/layers is in the XRSubImage, which you can't get outside the frame loop. It would be good if we could surface that information somewhere else (maybe just move those values off of the sub image and onto the layers or similar?) and in cases where we expect that the texture shape may change at runtime (which should only be projection layers, right?)

Maybe we can even provide a "reshaped" event? That way someone managing their own depth buffers can allocate it once and know that they don't have to constantly re-check the sizes each frame to see if they changes, and it allows texture allocation to happen outside the frame callback.

**Comment by cabanier** [comment]
> I apologize that I didn't see the relevant text in the spec when posting this. Seems that mostly addresses the issues I brought up. I will say that if feels like it may be a good idea to not request depth/stencil buffers by default? 

Yes, my latest proposal makes the dephtStencil format optional so no depth buffer is requested by default.

> > FYI The author can already get the width and height of the texture outside of the frame loop.
> 
> How? For non-projection layers you could infer it from the layer creation args, but otherwise the only time we explicitly report the image width/height/layers is in the XRSubImage, which you can't get outside the frame loop. It would be good if we could surface that information somewhere else (maybe just move those values off of the sub image and onto the layers or similar?) and in cases where we expect that the texture shape may change at runtime (which should only be projection layers, right?)

Oops, yes you are right. There is no way to get it outside of the frame loop.
We can't move it to the layers because not all layers (ie media) have a pixel width and height.
Do you think there's a need for such an accessor API? It was the author who set the pixel dimension so they could keep track of them or even put them in the layer object themselves.

> Maybe we can even provide a "reshaped" event? That way someone managing their own depth buffers can allocate it once and know that they don't have to constantly re-check the sizes each frame to see if they changes, and it allows texture allocation to happen outside the frame callback.

We don't allow layers to change their size. The only way to get a different sized layer is by allocating a new layer and replacing the smaller one.

**Comment by toji** [comment]
> We can't move it to the layers because not all layers (ie media) have a pixel width and height.

Good point, although maybe it only matters for Projection layers?

> Do you think there's a need for such an accessor API? It was the author who set the pixel dimension so they could keep track of them or even put them in the layer object themselves.

For most layer types, yes. The author doesn't set pixel dimensions for projection layers, though.

> We don't allow layers to change their size. The only way to get a different sized layer is by allocating a new layer and replacing the smaller one.

Sorry, I was conflating this with the base XRWebGLLayer which I think we allow the UA to resize at runtime. (I don't think any UAs do that, though).

**Comment by toji** [comment]
I'll do it, and close down this issue when it's up.

**Comment by toji** [comment]
Remaining discussion can now happen on #224. Closing
