### ISSUE TITLE
new interface for `updateRenderState'

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#24]
We want to pass in an array of layers into XRRenderStateInit.
What would be the best way to express this in IDL?

Should we extend the existing dictionary or should we create a new one?
```
dictionary XRRenderStateInit {
  double depthNear;
  double depthFar;
  double inlineVerticalFieldOfView;
  XRWebGLLayer? baseLayer;
  FrozenArray<XRWebGLLayer or XRLayer> layers;
}; 
```

@Manishearth what are your thoughts?

**Comment by Manishearth** [comment]
So WebIDL _does_ have `partial dictionary`, but it seems like it's generally considered a big mistake.

We have two options. We define `dictionary XRRenderStateInitLayers: XRRenderState` and in the layers spec "patch" `updateRenderState()` to accept this argument (this isn't exactly kosher iirc). Alternatively, we define a blank `XRLayer` interface in the core spec, `partial interface` it in the layers spec if necessary, and define a semantics-free `layers` array in the core spec.

**Comment by cabanier** [comment]
> So WebIDL _does_ have `partial dictionary`, but it seems like it's generally considered a big mistake.

A quick search in the Chrome codebase shows

> We have two options. We define `dictionary XRRenderStateInitLayers: XRRenderState` and in the layers spec "patch" `updateRenderState()` to accept this argument (this isn't exactly kosher iirc). Alternatively, we define a blank `XRLayer` interface in the core spec, `partial interface` it in the layers spec if necessary, and define a semantics-free `layers` array in the core spec.
> 
> I'd prefer the latter.

**Comment by cabanier** [comment]
> So WebIDL _does_ have `partial dictionary`, but it seems like it's generally considered a big mistake.

I find no current `partial dictionary` web interfaces in the chromium code base.
I agree that we shouldn't be the first one to add it.

> We have two options. We define `dictionary XRRenderStateInitLayers: XRRenderState` and in the layers spec "patch" `updateRenderState()` to accept this argument (this isn't exactly kosher iirc). Alternatively, we define a blank `XRLayer` interface in the core spec, `partial interface` it in the layers spec if necessary, and define a semantics-free `layers` array in the core spec.
> 
> I'd prefer the latter.

Yes and this change is very unlikely to break sites.
Can we still make normative changes to the WebXR spec?

**Comment by avaerkazmer** [comment]
There are rendering schemes that use a different depth discipline, such as Unity. Depth near and far doesn’t fully specify such cases.

This doesn’t really matter for the single layer case since depth reading is not required for functionality, but if we do such composition at the layer level then the difference between layers matters and thus would have to be handled in the dict.

Is this resolved yet or a separate issue?

**Comment by cabanier** [comment]
Depth near/far is used to calculate the matrices for projection layers.
I guess it could also be used to determine if a layers should be clipped if it's too close or far.

> There are rendering schemes that use a different depth discipline, such as Unity. Depth near and far doesn’t fully specify such cases.

I'm unsure what you mean. Can you explain or post a link to a site?

> This doesn’t really matter for the single layer case since depth reading is not required for functionality, but if we do such composition at the layer level then the difference between layers matters and thus would have to be handled in the dict.

non-projection layers are explicitly placed and content within them is not meant to interact with other layers.
 
> Is this resolved yet or a separate issue?

I think you should open a separate issue

**Comment by cabanier** [comment]
@Manishearth should we update the WebXR spec with a generic XRLayer?

**Comment by Manishearth** [comment]
IMO yes, but we should also have a `layers` array in `renderState` that does nothing in the base spec

**Comment by cabanier** [comment]
Maybe we should discuss it next week.
Should I put it on the agenda?

**Comment by Manishearth** [comment]
Sure. Perhaps you should make a strawman PR for this?

**Comment by cabanier** [comment]
@Manishearth I'm a bit stuck on how to do it. @toji , should we add the layers attribute to XRRenderStateInit in the WebXR or the Layers spec?
It seems more intuitive to have it in the structure after asking for the feature...

**Comment by asajeffrey** [comment]
One wrinkle is that the README says that "XRWebGLLayer functions as an XRProjectionLayer, but they are kept as distinct types for better forwards compatibility," but it is not obvious how to reflect this in the WebIDL.

One possibility would be to change `RenderState` and `RenderStateInit`:
```webidl
dictionary XRRenderStateInit {
  .. as before
  (XRWebGLLayer or XRProjectionLayer)? baseLayer;
  FrozenArray<XRWebGLLayer or XRLayer>? layers;
}; 
interface XRRenderState {
  ... as before
  readonly (XRWebGLLayer or XRProjectionLayer)? baseLayer;
  readonly FrozenArray<XRWebGLLayer or XRLayer>? layers;
}
```
(or use partial dictionaries and interfaces).

This is a breaking change though.

**Comment by cabanier** [comment]
We won't be changing `baseLayer`. That should stay as a `XRWebGLLayer`.
The README implies that they're interchangeable but we just meant to say that they can be used to accomplish the same effect. (= a render surface that covers your entire FOV.)

In our implementation we defined the following:

```webidl
 typedef (XRWebGLLayer or XRLayer) XRGenericLayer;

 dictionary XRRenderStateInit {
  double depthNear;
  double depthFar;
  double inlineVerticalFieldOfView;
  XRWebGLLayer? baseLayer;
  FrozenArray<XRGenericLayer>? layers;
};

**Comment by asajeffrey** [comment]
The READE currently says "Setting the layers array will override the baseLayer if one is present, with baseLayer reporting the first element in the layers array." So the `baseLayer` getter might return a `XRLayer` rather than an `XRWebGLLayer`?

**Comment by cabanier** [comment]
> The README currently says "Setting the layers array will override the baseLayer if one is present, with baseLayer reporting the first element in the layers array." So the `baseLayer` getter might return a `XRLayer` rather than an `XRWebGLLayer`?

I think that would be odd. I'd prefer it to return a null object.

**Comment by asajeffrey** [comment]
Well either way it's odd, if we have it return `null` then calling `xr.updateRenderState({ layers: [layer] })` will either set `baseLayer` to `null` or `layer` depending on `layer`'s type.

**Comment by cabanier** [comment]
If `layers` is not an empty array, `baseLayer` should always be `null`.

Calling `updateRenderState` with a `baseLayer` and a non-empty array should throw an error.

**Comment by asajeffrey** [comment]
> If `layers` is not an empty array, `baseLayer` should always be `null`.

The README says that `baseLayer` will report the first element in the layers array, so if the user writes:
```js
xr.updateRenderState({ layers: [layer] });
xr.requestAnimationFrame(() => {
    console.log(xr.renderState.baseLayer);
})
```
then what should be logged?
- always `null` (in which case we need to update the README)
- always `layer` (in which case we need to update the WebIDL)
- `layer` only when `layer` is a `XRWebGLLayer`

**Comment by cabanier** [comment]
I think we should update the README.

**Comment by asajeffrey** [comment]
OK, I'll submit a PR.

**Comment by Manishearth** [comment]
Alright, so concretely what I was suggesting was that, in webxr we make the roughly backwards compatible change:


```
dictionary XRRenderStateInit {
  double depthNear;
  double depthFar;
  double inlineVerticalFieldOfView;
  XRWebGLLayer? baseLayer;
  sequence<XRGenericLayer>? layers;
```

and in the core spec specify that setting layers is a NotSupportedError. Over here, we extend the base semantics.

It might be worth writing this in the form of a hook, i.e. upstream the spec says "if `layers` is set, `[=apply layers to the pending render state=]`", `and apply layers to the pending render state` is defined to just throw in the core spec (but we replace it here).

**Comment by cabanier** [comment]
> It might be worth writing this in the form of a hook, i.e. upstream the spec says "if `layers` is set, `[=apply layers to the pending render state=]`", `and apply layers to the pending render state` is defined to just throw in the core spec (but we replace it here).

That seems odd. Won't that break the linking?

**Comment by Manishearth** [comment]
Why would it break the linking? You can override it without actually replacing the link, you say "When the user agent is supposed to [=apply layers to the pending render state=], instead of doing the things defined in [webxr], perform the following steps:"

**Comment by cabanier** [comment]
OK. I will give try to update both specs.

**Comment by cabanier** [comment]
@Manishearth does that mean that `XRLayer` also moves to WebXR?

**Comment by Manishearth** [comment]
@cabanier yes, as an empty interface with no semantics

we can make XRWebGLLayer inherit from it

**Comment by cabanier** [comment]
@Manishearth I created https://github.com/immersive-web/webxr/pull/999 but I'm unable to add reviewers.

**Comment by cabanier** [comment]
These changes landed in both specs. Closing
