### ISSUE TITLE
Enable layers by default in the browser

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#258]
We at the Oculus browser team are considering shipping WebXR Layers by default.
- The spec is stable with no breaking changes for a long time
- our implementation is complete
- we have a repository with samples that cover most features
- there is some support in frameworks (ie aframe)
- we have a polyfill so authors can use the same codebase on UA's that don't support layers

We would like to know if anyone has strong opinions that we should not do this. If not, we would like to announce this to a broader audience so developers aren't caught off guard.

@toji @AdaRoseCannon @thetuvix @Manishearth @RafaelCintron @fordacious @jdashg @Yonet @cwilso  @jacobrossi @fe1ixz @davehill00 @dmliao

**Comment by AdaRoseCannon** [comment]
Oh fantastic! I don't have any objections that come to mind.

**Comment by Manishearth** [comment]
No objections, though it's probably time to start looking for TAG reviews and such?

**Comment by cabanier** [comment]
> No objections, though it's probably time to start looking for TAG reviews and such?

The Layers spec already went through TAG review: https://github.com/w3ctag/design-reviews/issues/528
I should have put that on the list :-)

**Comment by cabanier** [comment]
Also, we had a FPWD!
