### ISSUE TITLE
Behavior of getSubImage() with non-mono layers?

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#27]
The `getSubImage()` method is proposed to make rendering to mono layers more straightforward. I view this as a positive thing, but it leaves the question of what the behavior of the method should be for layers that aren't mono (projection layers or stereo non-projection layers.)

The two most viable options that come to mind are:

- Report the subImage of xrViewerPose.views[0].
- Throw an error.

Reporting the 0th view's image has the benefit of allowing developers to get at the texture quickly in the case of a single subdivided TEXTURE_2D or a TEXTURE_2D_ARRAY, allowing them to bind resources or viewports once in some cases. On the other hand, it could also contribute to bad assumptions if we allow different textures per view for TEXTURE_2D, or allow some developers to accidentally use a mono rendering path for non-mono layers. (Hard to fully prevent that type of developer error, though.)

**Comment by cabanier** [comment]
I think we should throw an exception.
If we special case it, the API might be more confusing.

> Hard to fully prevent that type of developer error, though.

Wouldn't it be obvious?

**Comment by cabanier** [comment]
@toji, the spec currently throws. Unless you object, I will close this issue

**Comment by toji** [comment]
I'm fine with it. Closing.
