### ISSUE TITLE
Add support for space warp

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#272]
Oculus submitted an [extension to OpenXR](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_FB_space_warp) to enable space warp.
This feature allows scenes to render at half the frame rate but with the use of smart reprojection, they can still render at full framerate.

To enable this, authors needs to submit a depth and a "motion" texture and with this information, the compositor can invent the missing frame. See [here](https://www.facebookconnect.com/en-us/session/232bf87c-fba9-47c0-9799-ba7d84ae03c2/) for a more in depth view and its advantages and drawbacks.

To enable this, I think we can introduce a new feature ("space-warp"?). If the feature is enabled, [XRWebGLSubImage](https://immersive-web.github.io/layers/#xrwebglsubimage) will have a new attribute that points to the motion texture.

**Comment by cabanier** [comment]
/agenda add support for space warp to the layers specification

**Comment by cabanier** [comment]
I added another PR for spacewarp: https://github.com/immersive-web/layers/pull/273
If we have time we can discuss.

/facetoface

**Comment by AdaRoseCannon** [comment]
We just assembled the agenda, we have some layers themed time on Friday afternoon if it's appropriate.

**Comment by AdaRoseCannon** [comment]
Curent schedule: https://github.com/immersive-web/administrivia/blob/main/F2F-April-2022/schedule.md#schedule

**Comment by cabanier** [comment]
I didn't know there was a deadline :-)
Can I add one more topic? It's not related to layers.

**Comment by AdaRoseCannon** [comment]
Can you drop it in an email to the chairs mailing list and we'll take a look at shuffling the agenda around next week to fit it in.

A PR directly to the agenda probably works too.

**Comment by cabanier** [comment]
Turns out someone else already put it on the agenda :-)

**Comment by cabanier** [comment]
@toji asked for some examples of space warp. Here are some articles:
- https://www.androidcentral.com/application-space-warp-samurai-slaughter-house-pc-vr-quest-ports
- https://uploadvr.com/quest-2-application-spacewarp/
- https://uploadvr.com/bonelab-120-hz-application-spacewarp/
Since we announce space warp, over 25 apps have launched that use it.

**Comment by cabanier** [comment]
This is now part of the layers spec and shipping in Quest Browser
