### ISSUE TITLE
Accessible Platform Architectures (APA) question on WebXR Layers API spec

### ISSUE THREAD

**Issue by RealJoshue108** [immersive-web/layers#278]
The Accessible Platform Architectures (APA) working group has reviewed the latest working draft of the WebXR Layers API Level 1 specification, and we wish to ask a question.

We would like to ensure that any re-rendering of text or other accessibility related content, does not result in these alternate formats being rendered at lower resolutions that may impact legibility.

The spec states:

"Legibility/visual fidelity The resolution for eye-buffers for 3D world rendering can be set to relatively low values, especially on low performance systems. It would be impossible to render high fidelity content, such as text, in this case."

Does this refer to text that relates to captions, or audio descriptions or alter alternative/accessible formats? Can you please clarify?

**Comment by cabanier** [comment]
I will reword that section. 
What I meant to say is that with *regular* WebXR, content may be rendered at lower resolution for performance reasons. With WebXR Layers, the user agent can render text at high resolution without the performance impact.

**Comment by RealJoshue108** [comment]
Thanks @cabanier - APA ack your response but there have been some questions raised about you mean by the term 'regular WebXR content'? For some in the group, there is a potential inference that this may mean that captions or alternate content is somehow 'irregular'. In the main though, we are also just not clear about what regular refers to, so please clarify, thanks.

**Comment by cabanier** [comment]
WebXR Layers extends the "regular" WebXR spec with support for timewarp layers.
When displaying captions in normal WebXR, they will look less sharp than when they are displayed on timewarp layers.

**Comment by RealJoshue108** [comment]
Ok, thanks for the clarification.
