### ISSUE TITLE
Alpha property for XRCompositionLayer

### ISSUE THREAD

**Issue by eXponenta** [immersive-web/layers#283]
Should be way to set alpha state to layer same as width/height or transform.

Reasons:

1. Native support for alpha fading for some effects without overheads. Because layers already has alpha blending by content alpha this is not a problem for implementation.

2. Optimisation. Due to that when we set alpha to 0 not needed draw a layer we can use this case for reduce calling updateRenderState for temporary layer disabling. 

Alpha fading can be implemented in current version only for non-media layers, because without fading layers can't be used in production code due to bad UX.

For regular layers need to use a middleware for each animation frame - draw content to canvas or framebuffer, apply alpha and upload it to layer, what is catastrophically slow for media layer emulatation when video is too large.

**Comment by cabanier** [comment]
/agenda allow author to control alpha on a layer

**Comment by cabanier** [comment]
Looking around other web APIs they seem to favor `opacity` over `alpha`.
We already have a `blendTextureSourceAlpha` attribute so maybe `alpha ` is fine.

**Comment by cabanier** [comment]
OpenXR also has support for color scaling: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_composition_layer_color_scale_bias

Would it make sense to allow that in WebXR?

**Comment by eXponenta** [comment]
Hm, because color scale already apply alpha,  in openXR it is right way to implementation.

**Comment by eXponenta** [comment]
#284
