### ISSUE TITLE
Extra blit required on XR devices with one framebuffer per eye?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#30]
The `XRWebGLLayer` interface https://immersive-web.github.io/webxr/#xrwebgllayer-interface provides a single framebuffer, with one viewport for each eye. When implementing this API for devices (e.g HoloLens or MagicLeap) which have a framebuffer for each eye, this means there's an extra blit where the WebXR framebuffer is copied into each device framebuffer.

Are there plans for an API which can be implemented on such devices without an extra blit? For example by having a method `getFramebuffer(view)` similar to `getViewport(view)` rather than a single `framebuffer` property?

**Comment by toji** [comment]
Moving to the layers repo because that's where this conversation turned pretty quickly, and I don't think there's any appetite to change how `XRWebGLLayer` is working in the meantime.

**Comment by cabanier** [comment]
Projection layers allow direct drawing into the destination texture which should address this request.

> The example at the beginning of https://github.com/immersive-web/layers/#rendering probably needs rewritten then. It's not obvious what glLayerFactory.getSubImage(layer) (the version without a view) is for.

@asajeffrey I rewrote that section. Can you take a look and let me know if it's clearer now?
