### ISSUE TITLE
Can webxr layers be used with WebGL1?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#33]
Looking over the examples in the explainer, it doesn't look like there's much coupling with WebGL2, just the use of the constant `gl.TEXTURE_2D_ARRAY` in `glLayerFactory.requestProjectionLayer(gl.TEXTURE_2D_ARRAY)` and the call to `gl.framebufferTextureLayer` for binding stereo layers. Should the API be usable in WebGL1?

**Comment by cabanier** [comment]
> Looking over the examples in the explainer, it doesn't look like there's much coupling with WebGL2, just the use of the constant `gl.TEXTURE_2D_ARRAY` in `glLayerFactory.requestProjectionLayer(gl.TEXTURE_2D_ARRAY)` and the call to `gl.framebufferTextureLayer` for binding stereo layers. 

Correct. Only texture arrays are specific to WebGL2

> Should the API be usable in WebGL1?

If you request layer with a texture array on a WebGL1 context, the call will fail.
If you request it with a regular texture, you will get either a separate texture for each eye or the same texture but with a different viewport. There's an example of this in the proposal.

**Comment by asajeffrey** [comment]
Yay! A couple of questions...

1. Would this mean in WebGL1, using webxr layers there'd be no way to use multisampling? So if a user wants to use multisampling they'd have to use the current opaque framebuffer side-by-side API?

2. Thinking about how we'd implement this on devices where the device's swap buffer provides a texture array, we'd need to allow a WebGL texture to be backed by either a GL texture, or a GL texture array plus an index?

**Comment by cabanier** [comment]
> 1. Would this mean in WebGL1, using webxr layers there'd be no way to use multisampling? So if a user wants to use multisampling they'd have to use the current opaque framebuffer side-by-side API?

That is correct. However @Artyom17 and Rafael Cintron are working on getting an extension in WebGL so you can still get multisampling support for the non-framebuffer case.

> 2. Thinking about how we'd implement this on devices where the device's swap buffer provides a texture array, we'd need to allow a WebGL texture to be backed by either a GL texture, or a GL texture array plus an index?

Yes, and I suspect that you'd still need a copy on those platforms.

**Comment by asajeffrey** [comment]
OK, so if the extension to support multisampling goes through, then users would be able to use `glLayerFactory.requestProjectionLayer(gl.TEXTURE_2D)` and still render multisampled stereo. That sounds great! There is still thje question of whether we can back a texture by an index into a texture array and still avoid the extra blit, but that's a problem that we'd need to try an implementation for. At lest we have a path to the sea!
