### ISSUE TITLE
Should `getSubImage()` take an XRFrame?

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#36]
I've been assuming that, much like the `framebuffer` attribute of an `XRWebGLLayer` is only complete during an animation frame callback that our new layer's sub images would only be retrievable during an animation frame. `getViewSubImage()` is already well designed for this, since we can validate that the `XRView` being passed in is for active `XRFrame` before returning an image, but `getSubImage()` (the mono variant) only takes the `XRLayer` right now. Passing in an `XRFrame` would help reinforce what context the API is intended to be used in and make the validation logic simpler.

**Comment by cabanier** [comment]
That sounds reasonable.
Is there spec text in WebXR that we could refer to wrt the "current XRFrame"?

**Comment by Manishearth** [comment]
The current frame has an `active` flag set internally. Using any other frame for stuff typically throws an InvalidStateError

**Comment by toji** [comment]
In the [opaque framebuffers](https://immersive-web.github.io/webxr/#opaque-framebuffer) section we indicate that the framebuffer shouldn't be considered complete outside of a `requestAnimationFrame()` callback, but that's a bit sketchy in terms of logic if you ask me.

The `XRFrame` has internal flags for [`active`](https://immersive-web.github.io/webxr/#xrframe-active) and [`animationFrame`](https://immersive-web.github.io/webxr/#xrframe-animationframe) that we can check, however, which is why I say the logic should be easier/cleaner if we supply the frame.

**Comment by Manishearth** [comment]
Yeah, sorry, to be clear I mean that if the user is supplying the frame it's very easy to check if it's active. We don't otherwise hold handles to the active frame anywhere.

**Comment by cabanier** [comment]
Should the spec text for `getViewSubImage` also make some reference to the current XRFrame, ie: 
`XRView which must be created by the current active XRFrame)`

**Comment by toji** [comment]
Yes. I think we'd want the text to be something like:

```
1. If the {{XRFrame}} which created |view| has an [=XRFrame/active=] flag set to <code>false</code> or a [=XRFrame/animationFrame=] flag set to <code>false</code> then [=reject=] ...
```

**Comment by cabanier** [comment]
@toji Sorry, I didn't see your suggestion before I did the PR.
Let me know if you prefer your suggestion and I will update the spec.

**Comment by toji** [comment]
No, your current text is fine. We probably do want to add a check for the `animationFrame` boolean as well, though, since we likely don't want to support returning new textures during other scenarios that surface an `XRFrame`, like `select` events.

**Comment by cabanier** [comment]
@toji see https://github.com/immersive-web/layers/pull/42
