### ISSUE TITLE
Why does requestQuadLayer and requestProjection layer require a GL target?

### ISSUE THREAD

**Issue by RafaelCintron** [immersive-web/layers#39]
Examples from the explainer:
````JS
const layer = await glLayerFactory.requestProjectionLayer(gl.TEXTURE_2D_ARRAY, { alpha: false });
const layer = await glLayerFactory.requestQuadLayer(gl.TEXTURE_2D, { pixelWidth: 1024, pixelHeight: 768, stereo: true });
````

Why do `requestProjectionLayer` and `requestQuadLayer` require a GL target?  Are we intending to expand these to be more than `TEXTURE_2D` and `TEXTURE_2D_ARRAY` in the future?  

If the intent is to communicate whether the developer wants a single texture vs an array of textures, seems straightforward to add this as an item to the dictionary passed as the second parameter: `texturearray: true`.

As an aside, how many XR runtimes prefer side-by-side rendering these days? If there aren't any, my preference would be to have new APIs like these always return texture arrays.

**Comment by cabanier** [comment]
> Why do `requestProjectionLayer` and `requestQuadLayer` require a GL target? Are we intending to expand these to be more than `TEXTURE_2D` and `TEXTURE_2D_ARRAY` in the future?
> If the intent is to communicate whether the developer wants a single texture vs an array of textures, seems straightforward to add this as an item to the dictionary passed as the second parameter: `texturearray: true`.

I don't think there are plans for any other objects. I'm happy to switch it to a boolean value.

> As an aside, how many XR runtimes prefer side-by-side rendering these days? If there aren't any, my preference would be to have new APIs like these always return texture arrays.

I *believe* we still do have a preference for side-by-side. @Artyom17 , what do you think?

**Comment by cabanier** [comment]
/agenda should we switch to a book and/or drop support for side-by-side textures?

**Comment by Manishearth** [comment]
I have a slight preference for making it into a boolean if we're never going to add more

**Comment by Artyom17** [comment]
I don't like the idea of boolean, it is not informative and poorly readable. I'd vote for using an enum, like "texture", "texture-array".

**Comment by RafaelCintron** [comment]
My strong preference is we have no enum or boolean and simply have layers standardize on texture arrays.  If we want to explore "cave" setups with more than two array entries, we can add an additional attribute where developers specify the number of layers on devices that support it.

**Comment by Artyom17** [comment]
Uhm.... Isn't this a bit extreme? From one point of view I agree with you, this will simplify implementation of UA and promote WebGL 2 into WebXR.
From other hand, it will complicate layers adoption since all current experiences are written to render as side-by-side stereo and re-writing it to texture array rendering is more difficult than render-to-(same side-by-side stereo) texture.
Also, for mono Quad, Cylinder and Equirect layers it doesn't make much sense to use texture array.

**Comment by RafaelCintron** [comment]
My preference comes from the fact that texture arrays are more performant on the platforms I work with.  If that the case for other platforms we expect implementations for, then I think we should standardize on them.  

If there are platforms where side-by-side is better, then we should give the developer a choice and add non-normative text about the performance differences they may encounter.  

For layers where the concept of "arrays" and "side-by-side" do not apply, we should eliminate the parameter altogether ... unless the parameter is going to control some other aspect of the layer.  In which case, my question in the title of the issue still stands.

**Comment by cabanier** [comment]
I'm unsure if we can leave WebGL1 behind. There are still a lot of frameworks and content written for WebGL1. Authors might also be more familiar with it.

afaik Safari still doesn't support WebGL2 so Apple might object.

**Comment by Artyom17** [comment]
The good thing about WebGL 2 is that it is mostly backward compatible with WebGL 1. I.e. you just change the 'webgl1' to 'webgl2' for getContext and everything continues to work w/o modifications.
However, proper porting WebGL 1 to WebGL 2 is a complex task, requiring shader modification to es300 version.

**Comment by RafaelCintron** [comment]
@cabanier Google is helping Apple add WebGL 2 to Safari.  I think WebGL 2 will land in Safari before WebXR does.  

Do you have data that which shows there is enough WebGL 1 WebXR content that we need to support side-by-side content for layers?  If so, I am OK with adding it back in with non-normative text that encourages developers to use texture arrays.

**Comment by cabanier** [comment]
I believe the vast majority of existing WebXR sessions are create with WebGL1 but that's just from inspecting popular sites. Dropping support for WebGL1 would make transitioning to WebXR harder for these sites.

Looking at [Chrome's statistics](https://www.chromestatus.com/metrics/feature/popularity) almost 10% of all pages use WebGL1 but only .15% use WebGL2.

> If so, I am OK with adding it back in with non-normative text that encourages developers to use texture arrays.

I'm ok with that.

**Comment by Artyom17** [comment]
One more argument against switching to texture arrays (only). I can render into a texture or multiview texture array with implicit antialiasing (yes, this will require additional WebGL extensions, but those extensions going to be directly mapped to corresponding GL extensions). I don't know such GL extension for non-multiview texture array (i.e. when glFramebufferTextureLayer is used).

**Comment by RafaelCintron** [comment]
@cabanier , the Chrome statistic you quoted shows how prevalent calling `getExtension` is in WebGL 1 vs. WebGL 2. WebGL 2 has fewer extensions, and less need to use extensions.  Many WebGL 1 extensions are core in WebGL 2 so it makes sense to me that developers would call `getExtension` in WebGL 2 fewer times than if they used WebGL 1. I do not believe there is a Chromium UMA that compares WebGL 1 usage vs. WebGL 2 usage all up.

Now, if you've single-handedly debugged a substantial number of WebXR sites and observed that a  they always call `getContext("webgl")` instead of `getContext("webgl2")`, then I am fine with supporting both if everyone is willing to do the implementation work that entails. We should also make it clear to developers that using WebGL 1 will not be as efficient as using WebGL 2 + multiview w/ texture arrays.  

> Meaning - there is no way to render directly into the non-multiview texture array with MSAA.

@Artyom17 , can you accomplish this by using multiview and adjusting the `baseViewIndex` passed to `framebufferTextureMultiviewOVR`?

**Comment by Artyom17** [comment]
>>@Artyom17 , can you accomplish this by using multiview and adjusting the baseViewIndex passed to framebufferTextureMultiviewOVR?

@RafaelCintron - uhm... It is actually an interesting question, I'll try! However, as you understand it will require the multiview multisampled extension to be supported by UA (and even non-MSAA multiview extension is not widely supported at the moment). But I like this idea anyway, will try it out and report back.

**Comment by cabanier** [comment]
@RafaelCintron I think the issue was address so I will close it. Please reopen if you feel like we need to discuss it more.
