### ISSUE TITLE
Set up Travis to auto-generate spec from bikeshed files upon commit to master

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#41]
Opening issue to remind myself to set this up like I have in the other repos so that @cabanier doesn't need to keep committing the rendered files.

**Comment by toji** [comment]
Okay, this is set up and looks like it's working. Any future pushes to the master branch will automatically update the HTML version accessible at https://immersive-web.github.io/layers/

Built HTML files should no longer be included in future pull requests. (Less work for everybody! Yay!)

**Comment by cabanier** [comment]
awesome! Thanks!
