### ISSUE TITLE
 Question on the high level goals of immersive web layers

### ISSUE THREAD

**Issue by hammerandtongs** [immersive-web/layers#44]
I have a question as to the higher level goals of layers (I'd likely develop layers via Threejs and Aframe) -

Would layers allow "holographic" or volumetric applications to share a common skybox(or lack of) and environment safely?

Example -
Music streaming player presented as a 3d interactable.
A user sizeable .25 meter collision sphere, moving a 6 axis controller into this sphere copies user inputs into the streaming applications "iframe" for manipulating the 3d interface of the streaming application.
The application has minimal needed knowledge of the user when the collision sphere isn't activated.
The application is subject to scaling/translation/opacity/et al. by the user.

This exists alongside other active web based applications like -

a 2d chat stream that might have 3d "emojis" inline in its 2d plane.

a 3d model editor with 2d and 3d objects and control surfaces embedded.

I realize layers probably lacks all the necessary moving parts but is it designed with this as an eventual goal? I see XRCubeLayer XRCylinderLayer...

**Comment by cabanier** [comment]
In short, yes this is what layers will eventually offer you.
The current proposal does not address having HTML 2D UI as part of your 3D scene but we're planning on adding that at a later stage.
It also lacks how hit testing is going to happen. We still need to figure that part out but IMO it's required.

Cube and Equirect layers can be used as skyboxes. They're common in VR but they could be used for AR as well.

**Comment by hammerandtongs** [comment]
Hmm... hit testing, do you mean what I was referring to as collision? If I was designing a holographic chessboard app I'd expect a normal xr input controller to just appear when the collision area was active and then handle its inputs then disappear when the controller moved out of the area(an area defined by the outside application)?

Thank you, I'm super excited this is finally happening! I have things I'd like to make for this world.

Are you aware of any document that has some terms, definitions and usecases for this? I feel like I'm having to invent words and expectations that should be written down already somewhere ie "holographic app"

**Comment by cabanier** [comment]
> Hmm... hit testing, do you mean what I was referring to as collision? If I was designing a holographic chessboard app I'd expect a normal xr input controller to just appear when the collision area was active and then handle its inputs then disappear when the controller moved out of the area(an area defined by the outside application)?

There is no normal controller or collision support in WebXR. 
Controllers are drawn by the author/JS framework as part of the scene and hit testing is done by the framework (not the browser).

In the layers case, controllers will be drawn into a projection layers which has similar properties to a  XRWebGLLayer (except more efficient) but since layers are drawn by the browser, it might be difficult for framework to detect hits on them.

> Are you aware of any document that has some terms, definitions and usecases for this? I feel like I'm having to invent words and expectations that should be written down already somewhere ie "holographic app"

We've listed some in the readme on the layers github and there's a presentation [here](https://github.com/immersive-web/administrivia/tree/master/F2F-Feb-2020).
The main reason for layers is efficiency, protected media playback and later on HTML layers

**Comment by hammerandtongs** [comment]
Thanks for taking the time @cabanier  

Can't tell you how much I'm looking forward to this. Most of the little demo and concept things I've done or seen all kind of scream "noone wants this if it draws the skybox".
