### ISSUE TITLE
Need to provide bias / scale for both eyes for stereo Equirect, Quad, Cylinder layers

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#48]
This issue is related to #46

When a single texture is used,  it is necessary to provide bias / scale for both eyes. Currently, only Equirect layer has that and only one pair of bias / scale.

How I see the Equirect layer:
```
dictionary XRTextureTransform {
  float scaleX = 1.0;
  float scaleY = 1.0;
  float biasX = 0.0;
  float biasY = 0.0;
};

interface XREquirectLayer : XRLayer {
  readonly attribute boolean stereo;
  //? readonly attribute XRStereoLayout layout;
  attribute XRReferenceSpace referenceSpace;
  attribute XRRigidTransform transform;

  attribute float radius;

  XRTextureTransform? getTextureTransform(XREye eye);
  setTextureTransform(XREye eye, XRTextureTransform? texture_transform);
};
```
If we agree on stereo layout then getTextureTransform will return the actual texture transform for the selected layout.
Otherwise, the setTextureTransform can be used to specify the transform for each eye. This method can be used to define custom layouts. 

Same stuff should be added into Quad and Cylinder layers. Or, maybe we can add directly to the base XRLayer? ProjectionLayer may just return null and ignore setTextureTransform.

**Comment by cabanier** [comment]
Looking at the OpenXR spec, bias and scale are only defined for equirect. Are you sure they are needed for cylinder and quad?

**Comment by Artyom17** [comment]
Well, the idea is to give a dev ability to specify custom stereo layout. That could be also achieved by letting dev to specify texture rectangles and just recalculate those into bias/scale internally.

**Comment by Artyom17** [comment]
I've asked Cass about why OpenXR has bias/scale only for Equirect and his response was:
"It probably has to do with when we proposed it, I would guess.  I agree they (Quad, Cylinder...) could both benefit from a scale / bias."

**Comment by cabanier** [comment]
> I've asked Cass about why OpenXR has bias/scale only for Equirect 

Does this mean that UA's that target OpenXR won't be able to implement this?

**Comment by Artyom17** [comment]
> > I've asked Cass about why OpenXR has bias/scale only for Equirect
> 
> Does this mean that UA's that target OpenXR won't be able to implement this?

A good question. I think, OpenXR might need to have another extension to implement stereo quad / cylinder layers from the same texture, yes. And Quad and Cylinder layers are already extensions, btw. I think, we need to talk to Cass.

**Comment by Artyom17** [comment]
Actually, there is a big chance that I am wrong and all we need is subimage.imageRect (in OpenXR terms). It is a bit confusing, I am trying to figure out if usage of the imageRect is all what we need here.  If this is the case, I'll close this issue.

**Comment by Artyom17** [comment]
Intermediate update: opinions are divided. Talked to two OpenXR guys in Oculus and their opinions are diametrically opposite on how OpenXR should handle subImage.imageRect: should it cause scaling / shifting of the specified imageRect to the whole visible area (eye buffer or layer boundaries) or not and whether OpenXR require additional extensions or not...

**Comment by cabanier** [comment]
Thanks for the update.
Let us know if you can get clarification. We'll wait to update the spec.

**Comment by Artyom17** [comment]
Ok, seems like I found a bug in OpenXR spec ;) subImage.imageRect supposed to be mapping the aforementioned rect to 0..1 (i.e. expand it to whole layer in each eye). Also, current equirect layer in OpenXR is going to be revised.

So, this issue is wrong, since I don't need bias/scale, but we might need a way to specify custom subImages for custom stereo layouts.
