### ISSUE TITLE
Hint 'static' for static layers?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#49]
There are layers which are not changing at all, for example 360 photos. In this case, compositor may save on GPU memory by allocating only one texture instead of full swapchain, which could be quite significant considering high resolution of such textures (4K x 4K). Would be great to have a hint 'static : true' provided at layer creation.

**Comment by cabanier** [comment]
Maybe we can add another factory that creates layers from images?
I think this is an optimization that can be added later.

**Comment by Artyom17** [comment]
I really think this is important feature to have in ver1 of spec. Just a simple example: hi res equirect or cubemaps. 
For equirect texture, let imagine we have 4096 x 4096 x 32-bit texture, i.e. 67,108,864 per texture. If it is not modified, we are talking about 65M * 3 (3 textures in a swapchain), i.e. 130M of graphics memory is wasted.
For cubemaps it is even worse. Let say, we have a cubemap with 1536 x 1536 x 32-bit face. I.e. each face takes 9,437,184 bytes and each cubemap has 6 of them. I.e. 56,623,104 bytes per texture. If we have  a stereo cubemap, it will be times two. And again, times 3 for the swapchain, i.e. overall graphics memory footprint is 339,738,624 bytes. Or, more than 200Mb of memory waste.

**Comment by cabanier** [comment]
Do you think it's important that you can draw to such a large surface with WebGL, or do you think it's enough if you could directly pass an image?

**Comment by Artyom17** [comment]
If it is 'static' then I need to draw or copy image into it just once. But the source of the image could be anything: it could be a canvas, it could be a PNG, it could be a texture....

**Comment by Artyom17** [comment]
(oops, pressed a wrong button)

**Comment by cabanier** [comment]
OK, so you believe we should have a layer that you can draw into once?

**Comment by Artyom17** [comment]
For Equirect and Cubemaps - yes. Maybe even for Quads and Cylinders it makes sense.

**Comment by cabanier** [comment]
/agenda should we allow layers that you can only draw to once?

**Comment by Artyom17** [comment]
So, static layers should still be updateable in the case when 'needsRedraw' flag is set (see #106)

**Comment by cabanier** [comment]
yes. When a static layer gets the event, it's supposed to redraw itself.

**Comment by cabanier** [comment]
There were no objections in this week's call to add this feature to the layers spec.
I can add it after addressing #83
