### ISSUE TITLE
Consider adding a layer creation factory to XRSession

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/layers#5]
[`XRWebGLLayer`](https://immersive-web.github.io/webxr/#xrwebgllayer) currently:
* Takes an `XRSession` in its constructor
* Has a static method `getNativeFramebufferScaleFactor()` that takes an `XRSession` as its only parameter - and thus only source of variability in the value returned

Given the importance of an `XRSession` to the creation of `XRWebGLLayer` (see https://github.com/immersive-web/webxr/issues/693) and the result returned by `getNativeFramebufferScaleFactor()`, one may wonder why `createXRWebGLLayer()` and `getNativeFramebufferScaleFactor()` are not methods on `XRSession`.

Even if that made sense, this wouldn't scale well as more layers are added because each layer type might require adding two methods to `XRSession`. One possible solution to this would be to expose a session-specific layer factory from `XRSession`. The `XRLayerFactory` could then have pairs of methods to create and getNativeFramebufferScaleFactor for each layer type. The presence of these methods would also allow support by the user agent to be detectable should the layers effort not provide another mechanism.

For example:
```
partial interface XRSession {
  XRLayerFactory XRSession::layerFactory()
};

interface XRLayerFactory {
  XRWebGLLayer createXRWebGLLayer(XRWebGLRenderingContext context, optional XRWebGLLayerInit layerInit);
  double getXRWebGLLayerNativeFramebufferScaleFactor();
};
```

/cc @toji @NellWaliczek in case there's anything they'd like to consider now in the base spec.

**Comment by toji** [comment]
This is effectively fixed with the latest proposal, right? Can we close it.

**Comment by Artyom17** [comment]
I guess so!
