### ISSUE TITLE
Is createProjectionLayer sync or async?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#57]
In the README, `createProjectionLayer` is called as an async function:
```js
const layer = await glLayerFactory.createProjectionLayer("texture");
```
but in the WebIDL it's a sync function:
```js
  XRProjectionLayer createProjectionLayer(XRTextureType textureType, XRProjectionLayerInit init);
```

**Comment by cabanier** [comment]
Yes, I missed some things during the refactor. I will fix it

**Comment by asajeffrey** [comment]
Thanks. I'm investigating implementing XR layers in Servo, you will probably get a steady stream of spec questions from me.

**Comment by cabanier** [comment]
Fixed with https://github.com/immersive-web/layers/commit/938cc402c74280ed12be830371b077cd7e8cd3eb
