### ISSUE TITLE
Some remaining references to promises in README

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#58]
There are still some references to promises in the README, for example "The method will return a promise that will resolve to the associated XRLayer type once the graphics resources have been created and the layer is ready to be displayed."

In the text "If a layer type isn't supported the returned Promise will reject," this will probably be replaced by throwing an exception - which exception?

**Comment by cabanier** [comment]
Fixed with https://github.com/immersive-web/layers/commit/8275e84f5a59fce6cb68ba2a52e4f87fe2407dd5
