### ISSUE TITLE
API allows creating more than one projection layer

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#59]
The API currently allows content to create more than one projection layer, and to decide which one to render at any point, for example:
```js
   let layer1 = glLayerFactory.createProjectionLayer("texture");
   let layer2 = glLayerFactory.createProjectionLayer("texture");
   ... render into the layers ...
   if (something) {
      xrSession.updateRenderState({ layers: [layer1] });
   } else {
      xrSession.updateRenderState({ layers: [layer2] });
   }
```
This is problematic on devices where the device has a swap chain that content is expected to render into. If the API only allowed one projection layer for each session, then we could arrange for that layer to be backed by the device swap chain, but since there may be more than one, it is not obvious what to do.

**Comment by cabanier** [comment]
[`updateRenderState`](https://immersive-web.github.io/webxr/#dom-xrsession-updaterenderstate) doesn't apply the changes right away.  Instead, it queues the changes until the next frame.

On platforms that can only provide 1 projection layers, you could reassign the swap chain during that time.
Alternatively, we could also change the spec so the UA can limit how many projection layers are created.

**Comment by asajeffrey** [comment]
Ah, that makes sense.

**Comment by asajeffrey** [comment]
OK, a follow-up question... is `layers` allowed to have more than one projection layer? It looks like the first layer is required to be a projection layer? In which case wouldn't it be a simpler API to have the `layers` API to contain all the layers apart from the base layer?

**Comment by cabanier** [comment]
> OK, a follow-up question... is `layers` allowed to have more than one projection layer? 

yes, you can have as many layers are you want, in any order.

> It looks like the first layer is required to be a projection layer? In which case wouldn't it be a simpler API to have the `layers` API to contain all the layers apart from the base layer?

No, you can have any layer as the first one and they will be rendered in order.
(Sorry that this isn't in the spec yet)

**Comment by asajeffrey** [comment]
OK, so projection layers aren't just for base layers, you can also do things like HUDs with them. OK.

**Comment by cabanier** [comment]
> OK, so projection layers aren't just for base layers, you can also do things like HUDs with them. OK.

Yes.
Do you want the spec to allow only create 1  or a limited number of layers?

**Comment by asajeffrey** [comment]
No, I think I can see how it works if `updateRenderState` only applies to the next rAF.

**Comment by cabanier** [comment]
ok. Do you want to close the issue? You can always reopen

**Comment by asajeffrey** [comment]
Ok
