### ISSUE TITLE
WebIDL for changes to XRRenderState and XRRenderStateInit

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#61]
Is the intention to add the `layers` field to https://www.w3.org/TR/webxr/#xrrenderstate-interface?
```webidl
dictionary XRRenderStateInit {
    ... as before
    FrozenArray<XRLayer>? layers;
};

[SecureContext, Exposed=Window] interface XRRenderState {
    ...as before
    FrozenArray<XRLayer>? layers;    
};
```

**Comment by asajeffrey** [comment]
Related: the WebIDL which would allow a `XRWebGLLayer` to be used in the `layers` array, c.f. #60

**Comment by asajeffrey** [comment]
I guess these should be specified as `partial dictionary` and `partial interface`.

**Comment by cabanier** [comment]
This is a duplicate of #24

**Comment by cabanier** [comment]
> Is the intention to add the `layers` field to https://www.w3.org/TR/webxr/#xrrenderstate-interface?

Yes, I'm unsure how to proceed. @Manishearth suggested to add it to the WebXR spec and not to use `partial`

**Comment by cabanier** [comment]
I will close this for now. @asajeffrey , can you add your comments to #24?
