### ISSUE TITLE
Why are `getViewSubImage` and `getSubImage` different methods?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#62]
It's not obvious why there are two methods, one for mono and one for stereo. Can we not have one method, but make the `view` argument optional?

**Comment by cabanier** [comment]
- We need the XRFrame to make sure we're in the correct state when calling `getSubImage`
- `getSubImage` always returns the whole image while `getViewSubImage` always returns a portion. It would be confusing to combine it in the same function.

**Comment by asajeffrey** [comment]
>     * We need the XRFrame to make sure we're in the correct state when calling `getSubImage`

Why does that not apply to `getViewSubImage`? Why does it not take a `Frame` argument too?

>     * `getSubImage` always returns the whole image while `getViewSubImage` always returns a portion. It would be confusing to combine it in the same function.

`getViewSubImage` is allowed to return a different texture for each view, with the viewport being the whole image. I thin "confusing" is subjective, I find the current API (where you need to call different functions depending on whether you're rendering stereo or mono) confusing!

**Comment by cabanier** [comment]
> 
> Why does that not apply to `getViewSubImage`? Why does it not take a `Frame` argument too?

Because `view` has a reference to its frame. See step 3 of the [algorithm](https://immersive-web.github.io/layers/#dom-xrwebglbinding-getviewsubimage)

> `getViewSubImage` is allowed to return a different texture for each view, with the viewport being the whole image. I thin "confusing" is subjective, I find the current API (where you need to call different functions depending on whether you're rendering stereo or mono) confusing!

If you want the whole image, call getSubImage (which can be stereo)
if you want part, call getViewSubImage.

Maybe the names are confusing and we should drop the `sub`...

**Comment by asajeffrey** [comment]
Oh I see, `getSubImage` is useful when you want to get the whole of a `stereo-left-right` or `stereo-top-bottom` image.

The current API does suffer from wanting to render content when you don't know whether the current session is mono or stereo, you need to write something like:
```js
for (let view in xrViewerPose.views) {
    let subImage = (
      layer.layout == "mono" ?
      glLayerFactory.getSubImage(layer, frame) :
      glLayerFactory.getViewSubImage(layer, view)
   );
   // Render from the viewpoint of xrView
}
```
because of step 2 of https://immersive-web.github.io/layers/#dom-xrwebglbinding-getviewsubimage

**Comment by cabanier** [comment]
I think you usually know if a layer that you're drawing into is stereo or not :-)

**Comment by asajeffrey** [comment]
Do you? I can imagine frameworks that share code between (e.g.) VR and AR, and having to use different methods to achieve the same result will complicated the code.

**Comment by cabanier** [comment]
/agenda should `getViewSubImage` work on mono layers?

**Comment by cabanier** [comment]
Thinking about this, I concur that `getViewSubImage` should work on mono layers.
I will update the spec.

**Comment by cabanier** [comment]
@asajeffrey please check #74. I set you as the reviewer.

**Comment by toji** [comment]
I think in the original explainer pass I did I listed this function (or it's equivalent at the time) as returning "the sub image that the given view will display", which still strikes me as a good way to frame it. For mono layers each view will be displaying the same sub image, but it's still something we can accurately report and so there's not a whole lot of reason not to.

#74 looks good in that respect.

**Comment by cabanier** [comment]
Thanks!
