### ISSUE TITLE
Issues with "determine the layout attribute"?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#65]
There are a number of issues with https://immersive-web.github.io/layers/#determine-the-layout-attribute

1. It's not used in the rest of the document.
2. It uses a"`WebGL2RenderingContext` context" but later says "If context is a `WebGL2RenderingContext`..."
3. It looks like upgrading from WebGL to WebGL2 can cause this to fail, which users may not expect, and may cause friction upgrading.
4. It took me quite a bit of reading to realize that WebGL1 contexts can use `"stereo"`.

**Comment by cabanier** [comment]
> 1. It's not used in the rest of the document.

yes, it is. Check https://immersive-web.github.io/layers/#dom-xrwebglbinding-createprojectionlayer step 17 and https://immersive-web.github.io/layers/#dom-xrwebglbinding-createquadlayer step 9

> 2. It uses a"`WebGL2RenderingContext` context" but later says "If context is a `WebGL2RenderingContext`..."
> 3. It looks like upgrading from WebGL to WebGL2 can cause this to fail, which users may not expect, and may cause friction upgrading.
> 4. It took me quite a bit of reading to realize that WebGL1 contexts can use `"stereo"`.

Those were bugs in the spec. Can you take a look at #67 ?

**Comment by asajeffrey** [comment]
I don't understand why I didn't spot those uses of "determine the layout attribute", ah well. Thanks for the fixes!

**Comment by cabanier** [comment]
> I don't understand why I didn't spot those uses of "determine the layout attribute", ah well. Thanks for the fixes!

No worries. Maybe it's because I aliased them? Also, bikeshed is only linking to one of them for some reason.

**Comment by asajeffrey** [comment]
Does https://immersive-web.github.io/layers/#dom-xrwebglbinding-createprojectionlayer mean we can only create stereo projection layers? Does this apply to AR sessions?

**Comment by cabanier** [comment]
> Does https://immersive-web.github.io/layers/#dom-xrwebglbinding-createprojectionlayer mean we can only create stereo projection layers? 

I need to update the spec to account for mono devices (such as phones). I will file an issue.
Projection layers should be mono there. 

> Does this apply to AR sessions?

I don't think AR/VR makes a difference for layers. Or are you thinking projection layers should be different for AR?

**Comment by cabanier** [comment]
Filed issue #68

**Comment by asajeffrey** [comment]
> I don't think AR/VR makes a difference for layers. Or are you thinking projection layers should be different for AR?

I was just thinking of AR as a common example of mono devices.
