### ISSUE TITLE
Determine the shape of Multiview support

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#7]
We've known for a while that we want to have support for multiview graphics extensions, but the previous attempt at it wasn't super well defined and the associated WebGL extension has yet to solidify. Additionally, we haven't yet come up with a concrete plan for antialiasing with multiview rendering, which is more-or-less a hard requirement for XR.

Planting this issue down as a way to indicate these problems still need to be solved while I remove the multiview stub from the explainer.

**Comment by cabanier** [comment]
@Artyom17 I believe multiview will just work with the new layers spec.
Let me know if that isn't the case; otherwise I will close this issue.

**Comment by toji** [comment]
That's my impression as well. Unless @Artyom17 has any concerns I agree that this should be closed.
