### ISSUE TITLE
What does "a session with layers enabled" mean?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/layers#72]
In https://immersive-web.github.io/layers/#updaterenderstatechanges, there is reference to a "session with layers enabled," with a link to https://immersive-web.github.io/layers/#dom-xrrenderstate-layers, which seems to imply it means a session whose render state has a non-null `layers` attribute.

Is this what's meant? Or does it mean a session created with the `layers` feature? If so, the link should be to https://immersive-web.github.io/layers/#layers

**Comment by cabanier** [comment]
That's correct.
I fixed it this morning in a pending PR #71 : https://github.com/immersive-web/layers/pull/71/files#diff-4197765c782d5938a43dc1de6d7b14ccR951

**Comment by asajeffrey** [comment]
Thanks!

**Comment by cabanier** [comment]
The PR was merged. @asajeffrey , let me know if this is still an issue in the spec.
