### ISSUE TITLE
Define behavior when no reference space is passed

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#75]
We also need to check if the space belongs to the same session

**Comment by cabanier** [comment]
@Manishearth Is there a way to say in webidl that an attribute can't be `null`?

**Comment by Manishearth** [comment]
attributes aren't null unless explicitly specified as such

where are we passing a reference space down during construction? I don't see anything of this sort.

**Comment by cabanier** [comment]
Most layers have a reference space.
I was wondering how we can define behavior when a null object or a space from a different session is passed.

**Comment by cabanier** [comment]
Can setters throw exceptions?

**Comment by Manishearth** [comment]
@cabanier right, I'm asking where these get initialized. There is no default reference space, we should probably ask them to be initialized at construction via the init dict

> Can setters throw exceptions?

Yep

**Comment by cabanier** [comment]
> @cabanier right, I'm asking where these get initialized. There is no default reference space, we should probably ask them to be initialized at construction via the init dict

They are initialized during layer creation time. See step 11 of https://immersive-web.github.io/layers/#dom-xrwebglbinding-createquadlayer

> > Can setters throw exceptions?
> 
> Yep

Great. I will define that an exception is thrown if a bad space or null is passed.

**Comment by Manishearth** [comment]
oh, my bad.

Does it make sense to default initialize them? I'd prefer having a required XRSpace parameter on the init dict, none of the defaults i can think of make a lot of sense. Defaults are great if using the default provides a desirable, common experience -- a layer being clipped into your face is not a desirable experience :smile:

**Comment by Manishearth** [comment]
Note that we can subclass dictionaries, so we can have

```
dictionary XRQuadLayerInit: XRLayerInit {
  required XRSpace space;
  float width = 1.0;
  float height = 1.0;
}
```

**Comment by Manishearth** [comment]
but also, i think `space` could just go into XRLayerInit

**Comment by cabanier** [comment]
I prefer to keep parameters that can be changed as attributes on the class.
Only `XRQuadLayer` needs an offset so it's not in your face. Maybe we can specify that it's 1 meter from the viewer?

**Comment by Manishearth** [comment]
@cabanier I don't think that's a good design pattern when there are no sensible defaults. Typically for an XRSpace (and interfaces in general) the only good default is "null", but null is not a state we can allow here.

I see most people immediately changing space after creation, which indicates that we should have it set at init.

**Comment by cabanier** [comment]
I suspect that a lot of authors will use "viewer" reference space with quad and cylinder layers and that the position will be constantly updated during the raf call (ie to do lazy headlock).

Equirect has to be a viewer space. I need to fix up the spec for that
Cube layers can be any space but I thank that almost everyone will just use the default viewer space with default orientation. 

Given this, I'm pretty sure that it's easier for the author to not have to put it in during initialization.

**Comment by thetuvix** [comment]
A key gotcha for quad layers is the big difference in reprojection behavior between a head-locked quad and a world-locked quad placed in the same location.

If an app is trying to render a video quad at a fixed place in the world, but `"viewer"` reference space is the default here, the app may just update the quad position every frame with the quad's pose in viewer space.  However, if the app does that, the quad will jitter badly, as reprojection will keep it head-locked rather than keeping it stable in the world.

In all other parts of the WebXR API, we have apps explicitly specify the `XRSpace` they intend to reason in.  For layers in particular, apps will be better off if we just have them explicitly set the relevant reference space on each of their layers, even if many layers end up in `"viewer"` space.  With that, the correct path for developers becomes the easiest: set their quad layer's reference space as their scene's core reference space, and then just set its position once.

**Comment by cabanier** [comment]
> If an app is trying to render a video quad at a fixed place in the world, but `"viewer"` reference space is the default here, the app may just update the quad position every frame with the quad's pose in viewer space. However, if the app does that, the quad will jitter badly, as reprojection will keep it head-locked rather than keeping it stable in the world.

Yes, for world locked content, the author should not be using a `viewer` reference space.
Do you think we should call that out?
(I'm also unsure what we should do if an `XRBoundedReferenceSpace` is passed in. Should we just ignore the bounds?)

> In all other parts of the WebXR API, we have apps explicitly specify the `XRSpace` they intend to reason in. For layers in particular, apps will be better off if we just have them explicitly set the relevant reference space on each of their layers, even if many layers end up in `"viewer"` space. With that, the correct path for developers becomes the easiest: set their quad layer's reference space as their scene's core reference space, and then just set its position once.

I'm unconvinced that it's a good idea to put the space in the `init` structure. I prefer APIs that are consistent and that don't offer 2 ways of doing the same thing.
However, if I'm the lone holdout, I'm happy to put it in.
So with the existing API, it looks like this:

```
let layer = xrGLFactory.createCylinderLayer("texture", {pixelWidth: 480, 
                                                        pixelHeight: 270, 
                                                        stereo:  "stereo" )});
layer.referenceSpace = myLocalSpace;
layer.radius = 5;
layer.centralAngle = 60;
```

With the new init structure it would look like:
```
let layer = xrGLFactory.createCylinderLayer("texture", {pixelWidth: 480, 
                                                        pixelHeight: 270, 
                                                        stereo:  "stereo" ,
                                                        referenceSpace: myLocalSpace;)});
layer.radius = 5;
layer.centralAngle = 60;
```

**Comment by Manishearth** [comment]
>  and that the position will be constantly updated during the raf call (ie to do lazy headlock).

This seems weird to me, what seems better is to anchor it to the local space with an originOffset of `getPose(viewer, local)` at the time of creation.

> In all other parts of the WebXR API, we have apps explicitly specify the XRSpace they intend to reason in.

Big +1 to this, this is why this threw me off initially.

> I'm unconvinced that it's a good idea to put the space in the init structure. I prefer APIs that are consistent and that don't offer 2 ways of doing the same thing.

It's not two ways of doing the same thing; one lets you set it at initialization, the other lets you update it dynamically later. Really, _most_ of the attributes on the layers should be constructed with subclassed init dictionaries; though in their case the rest of the fields can be optional and defaulted to reasonable values in most cases.

Having something in the init dict that is later reflected in a mutable attribute is a pretty common pattern in web APIs IIRC. It's less common for _immutable_ things; with the idea that the user can keep track of it themselves if they wish.

**Comment by cabanier** [comment]
> > and that the position will be constantly updated during the raf call (ie to do lazy headlock).
> 
> This seems weird to me, what seems better is to anchor it to the local space with an originOffset of `getPose(viewer, local)` at the time of creation.

A lot of layers that show interactive UI will be in "viewer" space because they want to be in view at all time. Headlocked content looks really unnatural which is why it should be updated in the Raf call.
...

> > I'm unconvinced that it's a good idea to put the space in the init structure. I prefer APIs that are consistent and that don't offer 2 ways of doing the same thing.
> 
> It's not two ways of doing the same thing; one lets you set it at initialization, the other lets you update it dynamically later. Really, _most_ of the attributes on the layers should be constructed with subclassed init dictionaries; though in their case the rest of the fields can be optional and defaulted to reasonable values in most cases.
> 
> Having something in the init dict that is later reflected in a mutable attribute is a pretty common pattern in web APIs IIRC. It's less common for _immutable_ things; with the idea that the user can keep track of it themselves if they wish.

OK. I will make the changes and post a PR

**Comment by cabanier** [comment]
@Manishearth @thetuvix let me know what you think of #80

**Comment by cabanier** [comment]
@Manishearth @thetuvix after @toji's comments in #78 I closed #80 and replaced it with #81 

We can revisit if we want to pass the space in the init after that lands.

**Comment by cabanier** [comment]
Filed issue #83

**Comment by cabanier** [comment]
@thetuvix You surmised it much better in #83. I will close this issue for now and we can pick it up there or if we open another one.
