### ISSUE TITLE
Add init objects for all layers? Or put all possible props to XRLayerInit?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#76]
Currently XRLayerInit contains only a subset of properties common for all layers. However, Quad, Cylinder, Equirect, Cube layers will need to have their own specific properties to be initialized. For example, Cylinder layer has { aspectRatio, radius, centralAngle }, Quad - { width, height }, Equirect - { bias, scale }. 
Should the spec define XRQuadLayerInit, XRCylinderLayerInit, etc?
Or, put all of these properties into XRLayerInit (which I am not fond of)?
Or, do not let init these props via init obj at all?

**Comment by cabanier** [comment]
The author can change the default properties after the layers is created.
The init structure is only there to pass information that can't be changed at runtime.

**Comment by Artyom17** [comment]
Oh, I see. Ok, I think it makes sense.
