### ISSUE TITLE
Define default values for all layers' properties

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#77]
The spec should define default values for all the properties of the layers which user does not change. For example, width / height for Quad layer, default pose, default angle, aspect ratio, radius for Cylinder, etc.

**Comment by cabanier** [comment]
The spec already defines them in the creation function 
For example, see https://immersive-web.github.io/layers/#dom-xrwebglbinding-createquadlayer

Do you think we should list the defaults with the layers as well? I was trying not to duplicate informatiion.

**Comment by Artyom17** [comment]
Ah, great, missed that!
