### ISSUE TITLE
Layers shouldn't have a `transform`

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/layers#78]
We already support origin offset spaces, layers don't need to have a "transform"

```
interface XRCylinderLayer : XRLayer {
  attribute XRReferenceSpace referenceSpace;
  attribute XRRigidTransform transform;
}
```

**Comment by cabanier** [comment]
You're right. I will remove the transform from the spec.

**Comment by cabanier** [comment]
This was covered during the discussion in #75 and solved with PR #80

**Comment by toji** [comment]
There's an important caveat here! Only `XRReferenceSpace`s can create offset spaces. This means that if you, for instance, wanted to attach a bit of UI to a controller's grip space you'd have no way to position it.

**Comment by cabanier** [comment]
@toji I think that means that PR #80 is not correct.
Instead, I should change from `XRReferenceSpace` to `XRSpace` and keep the transform.

**Comment by toji** [comment]
I think that using `XRReferenceSpace` rather than `XRSpace` in the first place was my mistake, and if we wanted to restrict layers to just reference spaces then this pattern would make sense. OpenXR doesn't have that kind of restriction, though, and I think we'd be preventing some interesting use cases if we limited it that way. So yeah, I agree that we should switch it to `XRSpace` and keep the transform.

**Comment by Manishearth** [comment]
Should we perhaps add a `getOffsetSpace` instead? I don't see why XRReferenceSpaces need to be special when it comes to offsets. We can still write it such that when given a reference space it returns a reference space (hooray inheritance)

**Comment by cabanier** [comment]
PR #81 is trying to address this issue.

> Should we perhaps add a getOffsetSpace instead?

That would be a change to the WebXR spec, right?
From the use case that @toji 's mentioned (offset a layer from the controller's grip space), it is easier to keep the transform separate. That way, all you need to do is pass the space into the layer and keep the `transform` as-is.

**Comment by toji** [comment]
That would be a change in the WebXR spec, yes. (The current function name is `getOffsetReferenceSpace()`) I don't recall why we decided that it would be best to limit that functionality to just reference spaces, but I do remember it being discussed. I think it was primarily a side effect of the main use for the function being perceived as teleportation around a scene, and also the fact that the closest equivalent in OpenXR was a `poseInReferenceSpace` being passed as part of the [`XrReferenceSpaceCreateInfo`](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/openxr.html#_xrreferencespacecreateinfo3).

I'm in favor of passing a space/transform pair here to avoid mucking with the core spec unnecessarily.

**Comment by Manishearth** [comment]
@toji We can use partial interface here to add it, though it would be a bit weird.

It feels very unfortunate to me that there are two ways to do transforms. But I guess that's fine.

We should have transform in the init dict as well, though we can make it nullable.

**Comment by cabanier** [comment]
> We should have transform in the init dict as well, though we can make it nullable.

Even though I added it yesterday, I'm still not entirely on board with that change. Let's merge #81 first and then we can continue to discuss it in #75

**Comment by Manishearth** [comment]
Sure.

**Comment by cabanier** [comment]
Merged.  Let's continue on the init structure on the #75
