### ISSUE TITLE
Video layer transport controls?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/layers#79]
Is the intention that the `HTMLVideoElement` is just used to manage the video to be displayed, or is it expected to render UA-provided transport controls on top of the video?

I would presume that any built-in UA video transport controls would be always hidden here, as supporting them would pull in lots of open questions around input focus of one or more controllers/hands within the scene.  If that's the case, we should write it down in the spec explicitly.

**Comment by cabanier** [comment]
Yes, it's only used to display the video stream, not the controls.
It's expected that the author provides a UI to control playback.

I didn't put any normative text in that section of the spec yet but I will make sure to call this out.

**Comment by toji** [comment]
That was my intent as well: The page would have to provide it's own controls.

**Comment by thetuvix** [comment]
Sure!  It's OK to dig in on this later.  I just know that `<video>` elements generally do end up with transport controls by default when in the main 2D document (and the chosen element may even be showing them at the moment if the element is still attached there and the mouse is over it), and so we'd need to specifically spec that UAs must hide them here.

**Comment by thetuvix** [comment]
Specifically, we may need spec coverage similar to the [Fullscreen API discussion in the DOM overlay spec](https://immersive-web.github.io/dom-overlays/#fullscreen-api-integration) to describe how that element may appear on other displays.

**Comment by cabanier** [comment]
> Specifically, we may need spec coverage similar to the [Fullscreen API discussion in the DOM overlay spec](https://immersive-web.github.io/dom-overlays/#fullscreen-api-integration) to describe how that element may appear on other displays.

I'm unsure if that's needed.
The way I imagined that this works, is that the layer is blitted with the video image source at the video's native frame rate.
