### ISSUE TITLE
Use Texture Arrays directly with WebGL 2

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#8]
This idea originated with an email that @RafaelCintron sent me a couple of days ago which was then discussed on the last WebXR call. In short, he proposed having a XR layer type that was WebGL 2.0-only that provided Texture Array's rather than the opaque framebuffer of our current `XRWebGLLayer`. (`XRWebGLLayer` would stick around for WebGL 1.0 compatibility.) Then the WebGL multiview extensions could use the texture array directly, which would more directly mirror the underlying native extensions like OVR_multiview.

I'm in favor of this approach, as it solves a couple of problems. Primary among them is that it would give developers the ability to mix geometry that is rendered via multiview techniques with geometry that is rendered one eye at a time. I believe that this is necessary because otherwise any single technique that a library uses that has not been converted to be multiview compatible would disqualify an app from using multiview at all (this is likely to be common, as the web ecosystem delights in mashing code from a variety of sources together.)

> Note: Even if we introduce a new layer type the plan would still be to only allow one layer at a time to be presented in the initial version of WebXR.

One point of misunderstanding in our initial discussion: I had assumed that this proposal was meant to wholly replace the previously planned method of multiview compatibility which was via the opaque framebuffer and could potentially support WebGL 1.0. I'm personally OK with the tradeoff of saying that multiview is a WebGL 2.0-only feature (this is the state of native OpenGL ES anyway.) @RafaelCintron and others apparently weren't ready to go that far and appear to be in favor of supporting both the Texture Array method and the opaque framebuffer method. That would lead to broader compatibility at the expense of complexity, both in WebXR and WebGL. (And again, the opaque framebuffer route is an all-or-nothing affair as currently specced.) In any case, I would be very interested in hearing from a variety of sources how big of a hurdle a WebGL 2.0 requirement for this feature would represent.

To kick off the discussion, here's a quick stab at the IDL to support this feature, all subject to copious bikeshedding. This variant omits multiview on the `XRWebGLLayer`, but that's ultimately dependent on the groups feelings on the above points.

```webidl
// I think it's important (and easy) to retain WebGL 2.0 compatibility on the "basic" layer type.
typedef (WebGLRenderingContext or
         WebGL2RenderingContext) XRWebGLRenderingContext;

dictionary XRWebGLLayerInit {
  boolean antialias = true;
  boolean depth = true;
  boolean stencil = false;
  boolean alpha = true;
  boolean multiview = false;
  double framebufferScaleFactor;
};

[SecureContext, Exposed=Window,
 Constructor(XRSession session,
             XRWebGLRenderingContext context,
             optional XRWebGLLayerInit layerInit)]
interface XRWebGLLayer : XRLayer {
  readonly attribute XRWebGLRenderingContext context;
  readonly attribute boolean antialias;
  readonly attribute boolean depth;
  readonly attribute boolean stencil;
  readonly attribute boolean alpha;

  readonly attribute unsigned long framebufferWidth;
  readonly attribute unsigned long framebufferHeight;
  readonly attribute WebGLFramebuffer framebuffer;

  void requestViewportScaling(double viewportScaleFactor);
  XRViewport getViewport(XRView view);
};

dictionary XRWebGLArrayLayerInit {
  boolean alpha = true;
  double arrayTextureScaleFactor; // Same as the framebufferScaleFactor
};

[SecureContext, Exposed=Window,
 Constructor(XRSession session,
             WebGL2RenderingContext context,
             optional XRWebGLArrayLayerInit layerInit)]
interface XRWebGLArrayLayer : XRLayer {
  readonly attribute WebGL2RenderingContext context;
  readonly attribute boolean alpha;

  readonly attribute unsigned long arrayTextureWidth;
  readonly attribute unsigned long arrayTextureHeight;
  readonly attribute unsigned long arrayTextureDepth;
  readonly attribute WebGLTexture arrayTexture;

  void requestViewportScaling(double viewportScaleFactor);
  XRViewport getViewport();
  int getLevel(XRView view);
};
```

A few things to point out in relation to the IDL:

- We would want the `arrayTexture` to be immutable, the same way the `framebuffer` is in `XRWebGLLayer`. I *think* we can get this by saying that it should be treated as if it were created with `texStorage3D`, which will naturally restrict the dimensions and format but not the texture parameters. Not sure if that's restrictive enough. If it is, though, it's much better than inventing Yet Another Opaque Type.
- As specced above this would be somewhat harder to use than the `XRWebGLLayer` because it makes the developer responsible for the framebuffer and all of it's attachments. That's generally a good thing for flexibility, but I'm curious if there's a good reason why we may still want user agent control of the depth or stencil buffers?
- In the IDL above I've moved `getViewport` off of `XRView` and onto the individual layer types for a couple of reasons: They're interpreted differently for each layer (all levels of the array share a single viewport, so you don't need to pass the view) and there may be other values that need to be queried only for that layer type (like the array texture level). To me it makes sense to group these queries on the layers themselves for flexibility, and it would help simplify some of the spec langauge to boot!
- I did add `getLevel` to the `XRWebGLArrayLayer` but it's not clear to me if that's useful or if we just want to say "texture level N is always associated with view N".

Let's hear everyone's thoughts on this!

**Comment by RafaelCintron** [comment]
Update on progress:
The [OVR_multiview2](https://www.khronos.org/registry/webgl/extensions/OVR_multiview2/) WebGL extension has been community approved.  The Chromium implementation on Windows has been turned on by default.  Firefox implements it on Windows and Android, also on by default.

We (Microsoft) are working on implementing [EXT_multisampled_render_to_texture](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_multisampled_render_to_texture.txt) in ANGLE and will use that as a foundation for implementing [OVR_multiview_multisampled_render_to_texture](https://www.khronos.org/registry/OpenGL/extensions/OVR/OVR_multiview_multisampled_render_to_texture.txt) in ANGLE.  Once that is complete, we look at exposing the OVR extension through WebGL.

**Comment by Artyom17** [comment]
Great to hear. Oculus Browser 6.2.x will already support OVR_multiview2 enabled by default (shipping ETA this week). Can't wait to have both  EXT_multisampled_render_to_texture and  OVR_multiview_multisampled_render_to_texture implemented in WebGL. The only issue - those (especially the multiview one) are completely intolerant to mid-frame flushes. Which may come, for example, from texImage2D (at least the way how it is implemented in Chrome: it switches framebuffers).

**Comment by cabanier** [comment]
Closing since this is resolved with latest proposal in WebXR and WebGL groups
