### ISSUE TITLE
Should each layer's referenceSpace just be space?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/layers#82]
A common use-case for a world-locked quad layer is to display a UI slate or video at a fixed point in the world selected by the user.  On devices that operate beyond room-scale, like a HoloLens, the app is likely to use the `"unbounded"` reference space and then make an [`XRAnchor`](https://immersive-web.github.io/anchors/#xr-anchor) on which to place their quad.

Apps should be able to specify an anchor space or any other space as the underlying space for their world-locked quad.  That then prevents the need to recompute and set the quad's location in the reference space every frame.

**Comment by cabanier** [comment]
Does #81 address your concern? It moves everything to `XRSpace`
