### ISSUE TITLE
Meaning of pixelWidth / Height when stereo is set to left-right or top-bottom

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#85]
What pixelWidth / pixelHeight should be set to for stereo left-right / top-bottom cases? Should it contain full texture size (i.e. include both views) or it should contain dimensions of a single eye?

For example, if pixelWidth / pixelHeight means dimensions of a single eye:
```
              cyl_layer = xrGLFactory.createCylinderLayer("texture", {
                pixelWidth: 1024,
                pixelHeight: 1024, 
                layout: "stereo-top-bottom")
              });
```
The benefit: no need to change W/H when changing layout.

And if pixelWidth / pixelHeight means dimensions of the whole thing (texture):
```
              cyl_layer = xrGLFactory.createCylinderLayer("texture", {
                pixelWidth: 1024,
                pixelHeight: 2048, 
                layout: "stereo-top-bottom")
              });
```
What is more convenient? The second approach is more convenient when the actual image dimensions are used instead of the hardcoded values:
```
              cyl_layer = xrGLFactory.createCylinderLayer("texture", {
                pixelWidth: textureWidth,
                pixelHeight: textureHeight, 
                layout: "stereo-top-bottom")
              });
```
Otherwise, it would be necessary to divide textureHeight by 2.

**Comment by cabanier** [comment]
Right now the spec states that the pixelWidth or Height should be doubled for side-by-side textures.
See step 4 and 5 of [Allocating color textures](https://immersive-web.github.io/layers/#allocate-color-textures).

**Comment by Artyom17** [comment]
It doesn't make much sense when just "stereo" specified for a single texture. What pixelWidth \ Height means in this case? It should mean dimensions of the single view, AFAIU.

**Comment by cabanier** [comment]
> It doesn't make much sense when just "stereo" specified for a single texture. What pixelWidth \ Height means in this case? It should mean dimensions of the single view, AFAIU.

When you specify `stereo`, you will either get 2 textures of the width and height, or a single texture with double the width or the height depending on what the UA prefers.
Either way, the `view` will always be of the specified width and height.

**Comment by Artyom17** [comment]
Ok. However, I don't see clear language in spec about that choice between two textures / single texture for 'stereo'.

**Comment by cabanier** [comment]
Let's say you want to create a quadlayer with `stereo` and a `texture-2d` texture.
You follow the steps found [here](https://immersive-web.github.io/layers/#dom-xrwebglbinding-createquadlayer)
In step 13, you run [determine the layout](https://immersive-web.github.io/layers/#dom-xrwebglbinding-createquadlayer) algorithm which can return "stereo", "stereo-left-right", "stereo-top-bottom" depending on what the UA prefers.
That result is then fed into the [allocate color textures](https://immersive-web.github.io/layers/#allocate-color-textures) algorithm.

**Comment by Artyom17** [comment]
Yeah, I got it about the single vs two textures, was my bad.

**Comment by cabanier** [comment]
So, there's still the question if the spec is doing the right thing when doubling the width or height if a side-by-side texture is requested.
An argument for the keeping it this way is that when you call `getViewSubImage`, you will get a viewport with the requested pixel dimensions.
However, @Artyom17 brought up that the main reason for this format is for pre-defined inputs and it's logical for the author to pass those input dimensions into the xrlayer creation API.

@toji , what do you think? Should we change the spec?

**Comment by toji** [comment]
I can see it both ways, but after thinking it through I definitely think this should be a "per eye" value (and the name should probably be changed to reflect that.) The primary reason for this is that with the "stereo" layout we've specified that the UA can choose whether or not to do a multi-texture or side-by-side layout. This means that if the width/height was intended to be texture side and not per-eye size you'd have one way to get a side-by-side layout where you have to give the doubled width and another way to (sometimes) get the exact same result but where you've given a single eye's dimensions instead. If we specify it as per-eye dimensions, though, then we consistently give the same values to get the same textures regardless of layout adjustments made behind the scenes.

**Comment by cabanier** [comment]
Thanks!
Can you think of a name to replace pixelWdith/Height that is not super long?
pixelWidthPerView feels too verbose...

**Comment by toji** [comment]
`eyePixelWidth` or `viewPixelWidth` maybe? `subImageWidth` would re-use some of our verbiage, but I'm not sure it suggests the right thing?

**Comment by Artyom17** [comment]
>>The primary reason for this is that with the "stereo" layout we've specified that the UA can choose whether or not to do a multi-texture or side-by-side layout.

Just a note: for "stereo" - yes, UA can decide. But for 'stereo-left-right' and 'stereo-top-bottom' - UA should either satisfy to the request or fail.

**Comment by cabanier** [comment]
> `eyePixelWidth` or `viewPixelWidth` maybe? `subImageWidth` would re-use some of our verbiage, but I'm not sure it suggests the right thing?

I'm ok with `viewPixelWidth`
