### ISSUE TITLE
Clarify cube layer

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#89]
I am implementing cube layer now and finding issues with the spec.
First of all, afaik, cube maps can be re-presented only as gl.TEXTURE_CUBE_MAP. Arrays of cube map textures (GL_TEXTURE_CUBE_MAP_ARRAY (https://www.khronos.org/opengl/wiki/Cubemap_Texture) afaik are not supported by WebGL 2.0

Secondly, need to define what pixelWidth/Height means for cube layer creation. I think this should be dimensions of the face. But in this case, it kinda makes no sense even to specify width and height, since the face is square.

Stereo cube maps can be implemented only by having two cube map textures (there is no way to share the same texture and no way to create an array). 

I'll keep updating this issue with new info I find about cube layers.

EDIT: Also, depth / stencil makes no sense for cube layers (probably also true for equirect).

**Comment by Artyom17** [comment]
'orientation' probably should be a DOMPointReadOnly:
```
interface XRCubeLayer : XRCompositionLayer {
  [RaisesException] attribute XRSpace space;

  attribute DOMPointReadOnly orientation;
};
```
The reason: it is important for UA to know when orientation is changed. If orientation is just a DOMPoint then it is harder to detect the change in cube map orientation.

**Comment by cabanier** [comment]
>  Also, depth / stencil makes no sense for cube layers (probably also true for equirect).

Why is that?

**Comment by cabanier** [comment]
#91 adds support for a  new texture type and changes `orientation` to `DOMPointReadOnly`

**Comment by Artyom17** [comment]
> > Also, depth / stencil makes no sense for cube layers (probably also true for equirect).
> 
> Why is that?

How do you see depth buffer working for cubemaps or equirects?

**Comment by cabanier** [comment]
> How do you see depth buffer working for cubemaps or equirects?

The idea behind providing the depth texture in the layers API is that some compositors might make use of this. Why would this apply to quad and cylinder but not equirect or cubemap?

**Comment by Artyom17** [comment]
>>The idea behind providing the depth texture in the layers API is that some compositors might make use of this.

Not only and not even much so. It is a helper mechanism to :
1) eliminate user error when creating a matching depth texture;
2) be able to perform some under-the-hood optimizations, such as depth buffer discard.

Using depth buffers for composition makes sense only for projection layers for final composition, IMO. And I believe OpenXR has depth layer extension for that only (https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_composition_layer_depth)

**Comment by cabanier** [comment]
According to [this article on stackoverflow](https://stackoverflow.com/questions/43634998/can-gl-depth-component-be-used-as-the-format-of-cubemaps) (see the update section) depth textures are supported for cubemaps.
@thetuvix , do compositors make use of the depth textures when displaying a cubemap? If so, I think we should have support for them in the layers spec.

It seems only WebGL2 support cubemap depth textures so maybe we should make this only work for that context.
