### ISSUE TITLE
Replace isLayerSupported by more sophisticated approach

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#9]
Klaus wrote:
I'm not sure about the boolean "isLayerSupported" - that's a hard question for the implementation to answer if it doesn't yet know what flags will be set on the layer and what size they'll be.

Alternatively, would it make sense to have a layer configuration attribute set that's provided to both the query function and the layer initializer? That way, there's less risk of inconsistency, and the implementation could potentially respond with "I could do this, but it's unlikely to hit target framerates". That could either be on a layer-by-layer basis, or potentially as a "here's my proposed overall layer configuration" all-at-once call.

**Comment by Artyom17** [comment]
I think to address this issue together with the issue #5

**Comment by cabanier** [comment]
Current spec rejects layer creation if the UA doesn't support it.
