### ISSUE TITLE
Clarify that `layers` feature can't be enabled mid-session

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#90]

**Comment by cabanier** [comment]
@Manishearth you stated that the `layers` could be enabled mid-session and provided [this link](https://immersive-web.github.io/webxr/#request-the-xr-permission).
That algorithm is only used by `requestSession`. Is there another place where it is used?

**Comment by Manishearth** [comment]
It's used directly by the permissions API: https://wicg.github.io/permissions-request/#dom-permissions-request

**Comment by cabanier** [comment]
That one is not implemented by any browser afaik

**Comment by Manishearth** [comment]
For XR? Not yet, but folks were planning to I think. Either way we should have this language in before people implement it :)
