### ISSUE TITLE
What should be the default attributes of all the layers?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#93]
Currently, I just picked some defaults but they might not be what people expect

**Comment by cabanier** [comment]
Current defaults:
Quad: width/height = 1 m, transform (1,0,0,1)
Cylinder: radius = 2, angle = pi/4, aspectRatio = 2, transform = default
EquiRect: radius = 1, scaleX/Y = 1, biasX/Y = 0
Cube: no defaults defined.

/ agenda pick reasonable defaults

**Comment by Artyom17** [comment]
Re-opening the issue for Equirect. I think the default radius for Equirect must be 0 (infinity). Any other value makes the equirect layer 'local' and it is more expensive to render. Local has to do per-fragment ray tracing to the sphere, where infinite does mostly vertex calculations (at least for Oculus' implementation). 

Current default value for radius is 10 m. We should make it 0.

**Comment by cabanier** [comment]
Unless anyone objects, I will make that change. 
I agree it makes more sense that the default equirect is infinite.
