### ISSUE TITLE
What should be the default space?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#94]
Currently, the layers specification sets the default `space` of cylinder, quad, equirect and cubemap layers to `viewer`.
As mention by @thetuvix in #83, this almost never makes sense because content should be anchored to the world and not the viewer's gaze.

Instead, `local` would be a much better default but there is no convenient place to borrow this space from the WebXR spec. Each session has a `viewer` space, but `local` or `bounded` spaces have to be created through a promise. Layer creation is synchronous so there is no way to run a promise as part of the creation algorithm.

Several people have mentioned it would be better if we pass the space during creation and that would be a clean way to solve it.
Unless there are objections, I will add `space` to the initialization parameters.
In addition, `viewer` spaces will be disallowed for equirect and cubemap.

Does this sound reasonable @Manishearth , @toji and @thetuvix ?

**Comment by Manishearth** [comment]
Big +1 on making it required on creation.

**Comment by cabanier** [comment]
See pr #95
