### ISSUE TITLE
Clarify that textures from layers are [most likely] immutable

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#96]
Since textures from the layers are pre-allocated they most likely are "immutable" (see https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf#nameddest=section-3.8.4). There are several consequences to that which affect how dev deal with such textures:
* all texImage* functions will fail with INVALID_OPERATION; texSubImage* must be used instead.
* copyTexImage* functions won't work either; copySubTexImage must be used.

Note, it doesn't matter if those textures are used in WebGL 1 or 2; it is a matter how those textures were allocated (via glTexStorage*, which is supported in GL ES 3.x / OpenGL 4.2, or via ARB_texture_storage extension for OpenGL ES 1.0, OpenGL ES 2.0, OpenGL 1.2 (https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_storage.txt)).

Probably, we would need to add "non-normative" section about it somewhere.

**Comment by cabanier** [comment]
No, this needs to be normative like it was done for [opaque framebuffers](https://immersive-web.github.io/webxr/#opaque-framebuffer).

**Comment by cabanier** [comment]
@toji can we normatively refer to that OpenGL ES spec?

**Comment by toji** [comment]
For WebGL 2 I think it's as simple as saying that the returned texture MUST act as if it were allocated with `texStorage2D/3D` and linking to the appropriate point in the WebGL 2 spec. WebGL 1 (as always) is the tricky one here. I'm not sure if we can/should indicate that a WebGL 1 context should operate according to the rules of a WebGL 2 concept, but it's probably not the worst way to approach it. Something like:

> Textures returned by `getSubImage()` and `getViewSubImage()` MUST behave as though they were allocated with `textStorage2D()` or `texStorage3D()`, as appropriate, even when using a WebGL 1.0 context.

Also worth noting that [EXT_texture_storage](https://www.khronos.org/registry/webgl/extensions/rejected/EXT_texture_storage/) was considered for a WebGL extension at one point but was rejected. Seems the reason for rejecting was simply "WebGL 2 is coming", though.

**Comment by Artyom17** [comment]
@toji We don't really need to expose the WebGL 1 extension since all texture allocations happen under-the-hood. As long as hardware supports either ES 3+ / GL 4.2 or the ARB_texture_storage / EXT_texture_storage - we are good.
I like the text you propose, @toji .
