### ISSUE TITLE
Define how spaces are handled for cube layers

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#97]
From @toji:
For XrCompositionLayerCubeKHR OpenXR's spec states::

> space is the XrSpace in which the orientation of the cube layer is evaluated over time.

Which pretty clearly indicates that only the orientation of the space is considered, and the cube will always be rendered with the view point at the center.

On the Oculus side, the PC SDK describes an ovrLayerCube as::

> Describes a layer of type ovrLayerType_Cube which is a single timewarped cubemap at infinity.

Which, again, is pretty explicit about the idea that position won't be considered when rendering.

**Comment by Artyom17** [comment]
Yes, so, what is the issue here?

**Comment by cabanier** [comment]
The issue is that the cubelayer only takes the position of the space into account; not the translation.
We need to update the spec to state this and also remove the check that disallows `viewer` spaces.

**Comment by Artyom17** [comment]
Yeah, I guess it makes sense to state that only orientation is used. As to viewer space - I don't see any use in using viewer space with cubmaps or equirects, tbh, so we can leave that check. Or can remove, I don't have strong opinion about it.

**Comment by cabanier** [comment]
ok. I will leave the checks in for now.

**Comment by cabanier** [comment]
@Artyom17 see pr #99
