### ISSUE TITLE
Define how spaces are handled for equirect layers

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#98]
From @toji:

OpenXR's spec makes it clear that the equirect is rendered as an in-world object and explicitly states that the back faces aren't rendered, implying you can actually move outside it. However:

> radius is the non-negative radius of the sphere onto which the equirect image data is mapped. Values of zero or floating point positive infinity are treated as an infinite sphere.'

So you CAN create a equirect layer that effectively negates the position and only considers the space's orientation, it's just not the only way to use the layer (unlike the cube map).

The Oculus PC API does not appear to have an equivalent layer type. The mobile SDK does, but I can't tell from the documentation how this case is handled.

**Comment by Artyom17** [comment]
Let me try to clarify the state of Oculus implementation of the "local equirects".

**Comment by cabanier** [comment]
OK. I will leave the spec as-is for now.

**Comment by Artyom17** [comment]
Ok, local equirects are supported by OpenXR implementations (both - PC and Mobile).

**Comment by cabanier** [comment]
ok, then we can keep the spec as-is and we can close this issue since it only calls out "viewer" as a limitation. Do you agree @Artyom17?

**Comment by Artyom17** [comment]
I agree
